### PR TITLE
Fix/210-Punctual donations

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Fixed puntcual donations so now you can perform them without Modheader.
To test this, just go to [http://localhost:3000/donaciones](http://localhost:3000/donaciones), complete the form and send it. If everything works, you will see a message telling you it went good. You can also check [http://127.0.0.1:8000/api/punctual-donation/](http://127.0.0.1:8000/api/punctual-donation/) in the api to see your new donations stored.

### CODE REVIEW

**Review by claugp06 — COMMENTED** [review]
Now it works as expected and I noticed trying this that suggestions have the same problem (not needing the token) maybe you could fix it also (it is fast and would not take much of your time)

**Review by marnunrey2 — DISMISSED** [review]
Perfect, it works now!

**Comment by FranciscoRossoR** [comment]
> Now it works as expected and I noticed trying this that suggestions have the same problem (not needing the token) maybe you could fix it also (it is fast and would not take much of your time)

I've tried but there might be some backend problem with this one, because I get an error saying
```detail: "Authentication credentials were not provided."```

**Review by marnunrey2 — APPROVED** [review]
still works, good job!

**Review by MartaInes — APPROVED** [review]
Iwas able to do a one time donation without problem. Good job!

**Comment by claugp06** [comment]
> > Now it works as expected and I noticed trying this that suggestions have the same problem (not needing the token) maybe you could fix it also (it is fast and would not take much of your time)
> 
> I've tried but there might be some backend problem with this one, or at least not the same problem than before, because I get an error saying `detail: "Authentication credentials were not provided."`

oki no problem maybe is because some get operation it is done or the permissions given are different

**Review by claugp06 — APPROVED** [review]
The punctual donations now works as expected good job!

**Pull request merged**
