### PR TITLE
Feature/54 asociationdropdown2

### PR DESCRIPTION
**Pull request by ivaramlar**
Implemented WhereWeAre and ColaboratorsEntities classes.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The screen for where we are does not follow the same style as the other screens. You should use the same container as the one in the home page.
The part of the entities that collaborates looks good and it is a good idea to include the link to navigate to them.

**Review by claugp06 — APPROVED** [review]
Now looks good. Well done.

**Review by claugp06 — APPROVED** [review]
Looks good, now you can merge

**Review by samrodman — CHANGES_REQUESTED** [review]
Looks good to me, well done. Just two minor things:
There seem to be two links to Dónde Estamos in the dropdown of the header (see image)
Also on the Where we are page you forgot the accent on Dónde.
image

**Review by manbarjim2 — APPROVED** [review]
Looks like good

**Review by fracalrod3 — APPROVED** [review]
I think it's fine

**Review by claugp06 — CHANGES_REQUESTED** [review]
The dropdown values appears two times
image

**Review by claugp06 — APPROVED** [review]
Looks ok now

**Review by samrodman — APPROVED** [review]
good now thanks

**Pull request merged**
