### PR TITLE
hotfix/auth-working

### PR DESCRIPTION
**Pull request by FelixoGudiel**
Multiple fixes have been added to the auth section.

-The times of the events have been corrected

-Now the student is added to the atendees section, allowing admins to check this updated value

-You can only add the authorization of children that are in that lesson

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
Everything seems ok now

**Review by pedlopruz — CHANGES_REQUESTED** [review]
I don't know if it's just me but I keep getting an error when authorising a student, basically to test it I have created an activity for Infantil which causes the authorisation to be sent to the family for them to accept it, but when I access as a family and I click on authorise I get this error "PUT /api/lesson-event/8/ HTTP/1.1" 403.

On the other hand, the dates have been corrected.

**Comment by pedlopruz** [comment]
When I give it to inspect I get this error {"detail": "You do not have permission to perform this action."}

**Comment by FelixoGudiel** [comment]
This is due to the backend code not being added yet. You may wait for it to be updated or fix this line in the views section of center-exit
image

**Review by pedlopruz — APPROVED** [review]
That was it, thanks for fixing it

**Pull request merged**
