### PR TITLE
Fix/144-main-page-information

### PR DESCRIPTION
**Pull request by samrodman**
On the main page (localhost:3000/) I noticed a button leading to the 'Conócenos' page and the 'Historia' page were missing. 

As far as I could tell, the description and the rest of the links are implemented and working.

### CODE REVIEW

**Review by MartaInes — COMMENTED** [review]
The buttons seem to be working just fine, but maybe the location could be improved. Maybe the "Leer más" one could be placed below the text, following the style of the others.

**Comment by samrodman** [comment]
Thanks for the feedback, Marta. I was wondering myself about the placement and whether it was better below, or on the right. I will do as requested as soon as I can.

________________________________

**Review by claugp06 — APPROVED** [review]
Good job approaching the feedback and making the changes

**Review by fracalrod3 — APPROVED** [review]
Thank you, it'd been bugging me for some time but I didn't quite know what the problem was, great job!

**Comment by samrodman** [comment]
I made a small change following Marta's comment. I believe it looks a lot better now.

**Review by claugp06 — APPROVED** [review]
It looks better now after the suggestions made by Marta

**Pull request merged**
