### PR TITLE
fix/242-volunteer-formation

### PR DESCRIPTION
**Pull request by marnunrey2**
I have fixed the volunteer formation so the volunteer has not have to see the formation every time it logges in after including the needed fields in the backend. To check this:
1. Register a volunteer in '/registrarse'
2. Complete the form of volunteer with the neccessary info
3. You'll see a wait page with status PENDIENTE. Log out
4. Log in as admin and accept the volunteer in 'voluntarios > solicitudes'
5. Log out and log in with the volunteer again.
6. You'll see the formation screen. Watch the videos 'til the end and click on 'Finalizar'
7. Now you'll see the volunteer's agenda
8. You can log out and log in again and see that the user is logged in directly to the agenda

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
Everything is working good job and also just taking the videos from youtube instead of having in the project is a better approach  as it reduces the size of the project!

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
I folowed all steps, but after watching all videos and clicking on "Finalizar" I logged out, then logged in again as instructed and I was shown the "Formación obligatoria de voluntarios" screen again.

**Review by MartaInes — APPROVED** [review]
Great job! I saw Fran comment, but in my case it's working fine. I logged out and in again, and it took me directly to the calendar.

**Comment by fracalrod3** [comment]
> Great job! I saw Fran's comment, but in my case it's working fine. I logged out and in again, and it took me directly to the calendar.

I'll try again then

**Review by fracalrod3 — APPROVED** [review]
Sorry, it didn't work because i wasn't using the 2 pm Back-end version, everything works like a charm, good job

**Pull request merged**
