### PR TITLE
Hotfix/62-activities-screens

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Fixed styles in all activities screens

### CODE REVIEW

**Review by MartaInes — CHANGES_REQUESTED** [review]
The style is looking way better. However, it would be nice if you could include the information that the NGO have in their previous page, eventho they'll send us updated information, but the format would probably be the same.
http://manosabiertasnorte.es/index.php/aula-de-convivencia/
For example, in this link the have a huge text explaining the activities in more detail.

Remember also to add the small description in the main activities page

**Comment by FranciscoRossoR** [comment]
Added new info to all activities screens.

**Review by claugp06 — APPROVED** [review]
Good goob!. The screens follows the same style as the other ones and the content include seems good.

**Comment by FranciscoRossoR** [comment]
Changed the info text format.

**Review by MartaInes — APPROVED** [review]
It's looking way better now, great job!

**Pull request merged**
