### PR TITLE
Feature/167 family daily and yearly evaluation

### PR DESCRIPTION
**Pull request by FelixoGudiel**
As a family, you can now see the evaluations, both daily and yearly of your kids. Check the sections "Evaluación diaria" and "Evaluación anual" when logged as a family.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The table it not really resposive an the content it not shown in the best way:
image
But I like the approach of how the content it is display
Also change the route redirection when log in of family to evaluaciones diarias and I do not know why but the "Niños" navigation does not work

**Comment by FelixoGudiel** [comment]
You are right.  I have fixed the responsiveness and made it clearer for the user to understand the grade. Here are some examples:
image
image
If you are thinking about another aproach to the visualization of the evaluation, do tell me! I am taking as a base the figma mocks and the availible data system

**Review by Ahydul — APPROVED** [review]
It works as expected. I don't see any error.

**Review by claugp06 — DISMISSED** [review]
Everything works as expected and the way the grades are shown makes it easier for the user to understand the system grade it has been used to evaluate their kids. Good job!

**Comment by FelixoGudiel** [comment]
Sorry, but merging changes have dismissed stale reviews. Please, check this branch and functionality again!

**Review by MartaInes — APPROVED** [review]
Everything seems to be working as it should. Good job!

**Pull request merged**
