### PR TITLE
Fix/82 styles

### PR DESCRIPTION
**Pull request by marnunrey2**
In this PR we have fixed every style to make it responsive and reduced the number of styles by collapsing the ones with similar styles, the same as with components. Also, the README is updated for any question that might appear later on and the links have been standardized.

### CODE REVIEW

**Review by manbarjim2 — APPROVED** [review]
After visiting all the existing screens, the style of all of them is correct and attractive. Great job also when organizing the code and urls.

**Review by claugp06 — APPROVED** [review]
Great work fixing the styles now they look attractive and works weel with smaller screen. Thanks for organizing the code. Good luck with thte Codacy issues

**Review by claugp06 — APPROVED** [review]
Now it passed the Codacy quality check

**Review by MartaInes — APPROVED** [review]
Looking good. Everything is responsive now. Great job!

**Pull request merged**
