### PR TITLE
fix/148 Extend MissionOverviewValues screen contents

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Added the complete text to Mission, Overview and Values sections in the corresponding screen.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The screen does not look that good. It is tru that the info of one of the containers it is much more and so it is show like that. Think on some other way so that it is shown better (summarise a bit also)

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
The values part is awfully long, either shorten it or change the screen's look to make it more appealing and easy to read.

You could try maybe putting another image below mission and vision and adding the values part just under it, for example.

**Comment by FranciscoRossoR** [comment]
Updated styles so the third container appears under the other ones in this screen.

**Review by claugp06 — APPROVED** [review]
Moving the container down makes that visually it looks better. Also, nice job checking that the containers are responsive for different screen sizes

**Review by fracalrod3 — APPROVED** [review]
Looks a lot better now, greatly done!

**Pull request merged**
