### PR TITLE
Fix/225 fix partner export

### PR DESCRIPTION
**Pull request by FelixoGudiel**
The download links for exporting are now working, I have changed the remaining "localhost:8000" to the api Endpoint, fixed a validator in meeting and removed the "organizacion" link

### CODE REVIEW

**Comment by marnunrey2** [comment]
The export for volunteers documentation in admin > voluntarios > solicitudes, it's not working

**Review by claugp06 — APPROVED** [review]
Good job with the fixed

**Comment by FelixoGudiel** [comment]
Perhaps you have tried with a populate entity, that does not contain real filles. Try with a created from scratch volunteer

**Review by marnunrey2 — APPROVED** [review]
It works, good job!

**Pull request merged**
