### PR TITLE
Feature/83-adminprofile-and-adminupdate-back-end

### PR DESCRIPTION
**Pull request by fracalrod3**
Everything works as intended:
image

### CODE REVIEW

**Review by samrodman — CHANGES_REQUESTED** [review]
Glad it works well, good job. I tested it a bit and i am able to update and also get the Admin correctly. I will suggest some minor changes I thought of as an outside user that I think would really improve the feature,

image
There's a strange blue color on the Actualizar perfil button that is not present in the next screen, so it should be easy to fix.


image
I believe having some placeholder values with the admin information here would simplify the task greatly of not having to type in all the info when you just want to update one thing, like the phone number.


Lastly, is the profile picture not ready to be updated yet? I'm assuming that's the case, please confirm! Thanks for the hard work.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
In process

**Review by samrodman — APPROVED** [review]
Good improvements on what I mentioned previously, thank you.

**Review by manbarjim2 — APPROVED** [review]
Works correctly.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Looks good, but you should resolve the merge conflicts

**Pull request closed without merging**
