### PR TITLE
fix/194-register and login functional without modheader

### PR DESCRIPTION
**Pull request by FelixoGudiel**
What I have done in this feature is fix the problem with register and login. The objective is to never have to use modheader in the frontend. 

I have spent most of the time fixing the conections, so perhaps there is a quick substitution that does not work. In this task it is very important to check all the functionality up to now works. Do not only check register and login, but your own functionalities.

If you find any problem, tell me so that I can work on it ASAP!

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
I have some small comments regarding your pr:
- The log in does not work I get this error even I active tha ccount or use an user of the populate (but the thing is that it return a status code 200)
image
-Secondly, the button for the checkbox should be the round one that were before
Also, you ask to try all funcionalities to see where it is no wokring I tried suggestions and gives a 401 error and also the register for partners gives a 401 error 
The rest I cannot try because I am not able to log in

**Comment by marnunrey2** [comment]
I get the same as claudia. It seams that the log in works because it gets the user but the toast error is shown. Probably, because of the is_enabled problem you said you were having. Hopefully backend will help you.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
I have tried different logins and it still does not allow me, both with populate.json users and registrations.

**Comment by FelixoGudiel** [comment]
I have found the source of the problem! It mainly had to do with token conservation. Also, I have checked logout and now fixed it! You should be able to log in as a user, try the functionalities and change to another one! I am scanning the project in search of these token errors, but if you find any in your worked sections, do tell me!

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Register, log in and logout works perfect! But I have registered as a volunteer and when loggin in and compliting the data I get user_not_found. Please, try to fix this so that the post for volunteers works okay
image

**Comment by FelixoGudiel** [comment]
You are right. Even though the call for the token is right, the page did not refresh and no token was loaded. The new function I have added shoudl fix this. Please look which pages need this change

**Review by claugp06 — COMMENTED** [review]
The register and log in seem to work for the different roles as supposed but I have a small question, the different screen like the ones from admin, volunteer or even suggestions and dontation give a 401 error I guess that it is because of the token not provided, could you look it up to ensure the tokens are include it ?
Also, just as some style preference I think the checkbox would look nicer if they would be rounded as before but apart of that everything looks really good and working.Great job.

**Comment by marnunrey2** [comment]
> You are right. Even though the call for the token is right, the page did not refresh and no token was loaded. The new function I have added shoudl fix this. Please look which pages need this change

Thanks for the change, now it works! However, when loggging in as admin, the screens fetching the data is not working because authentication is not being sent. Could you check that?

**Comment by manbarjim2** [comment]
I have successfully logged in as an administrator, volunteer and family.
I have been able to log out 3 times.
I was able to register as a volunteer successfully.
But when the profile data is loaded for the first time, the previously registered email appears (once reloaded, the correct email appears).
Also, as María says: the screens that display the data do not work because the authentication is not sent.

**Comment by FelixoGudiel** [comment]
I have systematically looked at all the pages in search of errors and I think I've got them all! Please try and tell me!

**Review by marnunrey2 — APPROVED** [review]
Perfect, everything seems to work!

**Review by claugp06 — APPROVED** [review]
I have look over the different screen wich might require the use of a header and it seems fine. Really good job fixing the log in and register.

**Review by manbarjim2 — APPROVED** [review]
congratulations, you did a great job solving this task! Everything seems to work correctly.

**Pull request merged**
