### PR TITLE
Feature/124 partners screen

### PR DESCRIPTION
**Pull request by MartaInes**
This PR contains the Calendar screen for Partners. Initially they were supossed to have 2 screens, one for the general activities of the NGO and another for the meetings. I decided to unify them for simplicity for them. If you realize it, you can not add yourself to an event, because it wouldn't make sense. I also change the menu to add the membership field, so we can add there the option to change how much are you paying and how often.

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
It looks as aspect and the idea of joinning activities and meetings on the same calendar it is a nice approach. When the event calendar it is updated it the meetings created  should also appear on it as well.

**Comment by samrodman** [comment]
I also agree it's a good idea to have it all in one screen for the calendar, the same goes for Admin events. I have two comments about what I am seeing: the meetings aren't fetched yet from what i see in the code, this will be added later? And lastly, if you could make the calendar a bit wider that would be great!
I should have the latest version running, but let me know if it's different for you.

**Review by samrodman — APPROVED** [review]
Nice job and good idea combining two calendars in one, but please check the comment i left before just in case! Thanks.

**Comment by manbarjim2** [comment]
It seems to me to be a very good way to solve, sometimes it is not necessary to follow what the task asks for and it can be solved in another, more efficient way.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
In the code there are selectedEvent and showRegisterForm, I understand that this is not necessary. This makes it possible to select the events, and you said that it was not necessary.

**Comment by manbarjim2** [comment]
Unselected:

image

**Comment by manbarjim2** [comment]
Selected:

image

You can see that the color changes.

**Review by manbarjim2 — APPROVED** [review]
All is correct.

**Pull request merged**
