### PR TITLE
fix/129-admin-families

### PR DESCRIPTION
**Pull request by marnunrey2**
Fixed the admin families and admin families requests with the new backend and totally responsive. 

On admin families, you can see:
- the family name and number of kids accepted on the left
- kids info on the right (pending what info does the ong manager want to see of the kids)

On admin families requests, you can see:
- the avatar of the student (not yet properly displayed because backend does not have photos)
- buttons for downloading the enrollment document of the student, acepting the student and rejecting the student (there is currently a window alert because these implementations are not made yet in the backend)

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
Looks good. Maybe in the future we have to get back depending on the request of the NGO

**Review by samrodman — CHANGES_REQUESTED** [review]
Great work, it's basically working perfect as I can tell. I have a small suggestion, maybe we could put the family name in bold so it can be seen better.

Also i noticed Evaluacion is missing an accent on the cards, and finally I noticed that the first card has more spaces in Nombre de Niño than the others:
image

**Comment by marnunrey2** [comment]
> Great work, it's basically working perfect as I can tell. I have a small suggestion, maybe we could put the family name in bold so it can be seen better.
> 
> Also i noticed Evaluacion is missing an accent on the cards, and finally I noticed that the first card has more spaces in Nombre de Niño than the others: image

Added the accent and the bold style, about the spaces between one Nombre niño it's because the p has a justify style and looks better for the rest of the kid info. As soon as I get the information the admin wants to see, I will make the styles better.

Thanks for pointing it out!

**Review by samrodman — APPROVED** [review]

**Comment by samrodman** [comment]
very nice María, thanks

**Pull request merged**
