### PR TITLE
Fix/173 admin families requests

### PR DESCRIPTION
**Pull request by ivaramlar**
Now, the bottom to accept and refuse a request are functional. To test the download feature, it is necessary to create a new student with status = "PENDIENTE" and valid files.

### CODE REVIEW

**Comment by FelixoGudiel** [comment]
There are merge conflicts, please check them. Also, how am I expected to create an admin account?

**Review by claugp06 — CHANGES_REQUESTED** [review]
Fix the merge request first of all and try to give a more clear explanation of how to test this pull request

**Comment by ivaramlar** [comment]
First, It is necessary to create an admin user and a student with status "pendiente" in http://127.0.0.1:8000/api/auth/users/, next you need to activate both accounts and redirect to http://127.0.0.1:8000/api/auth/jwt/create to get a token to be able to register as an admin. 

Finally, you need to go to admin family'request, and you will be able to manage download, accept and refuse.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Everything works as expected and the file download,really good job. Just a small detail I noticed is that a toast sucess for accepting/rejecting the family should be included it because it is one of the comments made from the pilot user that would be nice to include.

**Review by FelixoGudiel — APPROVED** [review]
Works as expected, I would try to fix the placeholder image though, if you have time.

**Review by FranciscoRossoR — APPROVED** [review]
Everything seems to work as intended, well done.

**Pull request merged**
