### PR TITLE
feature/53-Transparency

### PR DESCRIPTION
**Pull request by MartaInes**
This PR contains the Transparency screen from the homepage. The only thing left to do is to link the different documents to the database so when you click on them you can download them. Right now they take you to a random document.

### CODE REVIEW

**Review by samrodman — CHANGES_REQUESTED** [review]
It looks very nice, only two small things I want to point out just in case:
1. The transparency text box takes up the middle of the screen when we change the window size.
2. The image background could maybe be closer to the header so that when it's rendered, there is no white space ? this is not anything major though.

here is my screenshot on Firefox 123.0 and Linux Mint.
image

**Review by claugp06 — APPROVED** [review]
It looks good and the color chosen for the table component follows the ones commented by the NGO. It is true that the component showing the title it is not 100% resposive but this can be fixed netx so we have somenthing to show the NGO after the srpint.

**Review by samrodman — APPROVED** [review]
thanks for the minor fix, looks very good

**Review by samrodman — APPROVED** [review]
everything is fine, all good.

**Review by claugp06 — APPROVED** [review]
Good job dealing with the conflicts.

**Review by manbarjim2 — COMMENTED** [review]
Everything seems correct

**Pull request merged**
