### PR TITLE
Feature/91-volunteersAttendence + Feat/128- Volunteer ageda unsubscribe

### PR DESCRIPTION
**Pull request by manbarjim2**
image

Describe the solution you'd like
The volunteer can see the event name and date of an event that she/he assist
Additional context
For style doubts you can always look the mockups.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
If the volunteer only went to one activity, the container with the box should be shown centre and in top of the web page. The way it is done now seems like the space of the screen it is not used it the most smart way.
I just check it and the data it is display correctly I was sig in as other volunteer which does not have any data. You coul add a text indicating somenthing like you have not participated in any activity or somenthing like that. If more than one event it is shown are they display one next to other like in lessons screen in admin or not? Make sure of it

**Review by samrodman — DISMISSED** [review]
Remember to fix the conflicting files and make the requested changes otherwise the functionality works!

**Comment by samrodman** [comment]
Remeber to solve the conflicts and act on the requested changes

**Comment by manbarjim2** [comment]
> There is some errors in the code. Even the data it is taken correctly from the backend nothing it shwon in the screen taking the last changes.Please make sure it works. Also the component of the menu side should appear in the centre and the blue line until the end but it is not shown like that.

image

I think the data is taken correctly. And I have taken the existing Layout for the sidebar. Should I create a special Layout just for this screen? I may be wrong, please resolve my doubts.

**Comment by claugp06** [comment]
> `[feature/91-VolunteersAttendence](/ISPP-G5/NexONG_Frontend/tree/feature/91-VolunteersAttendence)`

Which Volunteer have you you se so I can see if the data it is displayed correctly. About the layout, you do not need to create a customized one just make sure it fits as expected.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Make sure that the layout of the blue cards appears one next to other as some other screeens
image

**Review by claugp06 — CHANGES_REQUESTED** [review]
It looks good now and it works. Don´t worry about the issue with the menu on the side

**Review by claugp06 — APPROVED** [review]
Great job fixing the problems

**Comment by samrodman** [comment]
Hi! Please fix the styles asap by the way, and I will check your PR now

**Comment by samrodman** [comment]
Hi, sorry, I have a lot of conflicts when trying to open this PR, I think if they need to be fixed but I'm not certain.

**Review by ivaramlar — DISMISSED** [review]
The botton of delete doesn´t work, maeby is caused by changes that have been done 
Captura de pantalla 2024-03-22 155240
 in backend.

**Comment by claugp06** [comment]
> The botton of delete doesn´t work, maeby is caused by changes that have been done Captura de pantalla 2024-03-22 155240 in backend.

The code works as it is expected. The reason you are not seen it working is because you have not created an authentication as indicated by the backend. Please, do it an review this PR again

**Review by samrodman — APPROVED** [review]
Well done, fix the conflicts like we said and you are set!

**Review by claugp06 — APPROVED** [review]
Good job,fixing the conflicts

**Pull request merged**
