### PR TITLE
Feature/191 partners membership

### PR DESCRIPTION
**Pull request by samrodman**
In this pull request, in the profile of the Partner (Socio) which has been created, we have two buttons which we can use to renew the membresy type or we can also drop out as a partner. 

I don't quite understand the process for dropping out, and I'm not sure if everything is ready on backend side to send the email or how to do it to confirm the deletion. Also, I have doubts as to why when i press on perfil in the header it takes me out to the main page, so navigate with socio/perfil please. If anyone can answer these questions it's greatly appreciated

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
I think the problem with the redirection it is related with the same problem as the log in redirecting to the home page, it will be fixed and this should be also fiexed by that.
From the funcionality:

1. The membership button it not needed as the info it is on the profile screen
2. The button are too big they should be smaller
3. I tried to create a cuota but it is given my an error of wrong IBAN number but the formart it is correct and also I do not get errors in network or console so I do not know the issue
Apart from that for the delete, in the backend there is a delete method for doing this function if you have any doubt contact the backend team leader he might be able to give you a more clear response
Good job!

**Comment by samrodman** [comment]
I fixed the issues you mentioned, the iban check is done with npm install iban
Then i import it in the file.

**Review by FranciscoRossoR — CHANGES_REQUESTED** [review]
I can only change my donation once, because after that I get
```"donation with this iban already exists."```
So, maybe it should be a PUT instead of a POST so I can update my existing donation?

**Review by claugp06 — CHANGES_REQUESTED** [review]
Is there no way to be redirect directly to the route or fixing it?

**Comment by samrodman** [comment]
> Is there no way to be redirect directly to the route or fixing it?

i couldn't figure it out, i simply put the corresponding layout and headers for 'socios' , and it should work if i'm not mistaken

**Comment by samrodman** [comment]
> I can only change my donation once, because after that I get `"donation with this iban already exists."` So, maybe it should be a PUT instead of a POST so I can update my existing donation?

i made changes to solve this problem, i might have a good lead but apparently patch and put is forbidden with error code 403 for partners, so this I think is not correct. If a partner wants to edit his donation then it should be allowed.

**Review by ivaramlar — CHANGES_REQUESTED** [review]
I have tested the pr, and y I have found an error when the perfil's button is clicked, the error is related to length function.

**Review by claugp06 — CHANGES_REQUESTED** [review]
First of all, quite a good job but I would like to comment about some topics: 

1. In "Baja" I woul put the message informing about the email above instead of where it at the moment.
2. Also, I could change the data of a partner and how much it is donated but not confirmation message it is shown 
3. Just as a personal opinion and regarding the style maybe it is nicer to show the buttons next to each other but i do not know

**Comment by samrodman** [comment]
> First of all, quite a good job but I would like to comment about some topics:
> 
>     1. In "Baja" I woul put the message informing about the email above instead of where it at the moment.
> 
>     2. Also, I could change the data of a partner and how much it is donated but not confirmation message it is shown
> 
>     3. Just as a personal opinion and regarding the style maybe it is nicer to show the buttons next to each other but i do not know

Thank you for the feedback, I'll make some small style changes and I'm aware of the implementation not being complete. Still need the backend to be finished but I was able to try with a backend hotfix branch and it seems to work. I'll let you know ASAP

**Review by claugp06 — CHANGES_REQUESTED** [review]
I tried the functionality using the hot fix branch of the back. The registration part of partners indicating the amount to donate works as expected, really god job!. 

In the part of the profile, I tried t change the amount of donated but it gives an error:

> Detail not found
Also, the input box for the quantity is maybe to big for the data that is introduced.
And the "Baja" part does not work neither

**Review by ivaramlar — DISMISSED** [review]
I have tested, and every thing is okay, excepted the changes that Claudia has asked. I am not able to check the pr out later, so I am going to approve to avoid problems.

**Comment by samrodman** [comment]
After reviewing with other members and the TL, to test this PR you must do the following:
1. create a new partner and fill out the form, you will now see the donation form is added so that when you become a partner, there is a donation created.
2. Go to profile of the partner once logged in. Since the partner can have one donation, if you go to renovar o cambiar cuota, you will see your donation info and you can apply patch to it!
3. About the Baja, we are shuffling whether to just use the delete user button from profile, since it doesnt make much sense to delete your donation and continue being a partner.

**Review by claugp06 — APPROVED** [review]
Now everything works as expected nice job !

**Review by FranciscoRossoR — CHANGES_REQUESTED** [review]
I can change the parameters in the form, but when I click "Finalizar" nothing seems to happen, and if I log out and in again and go back to my donation screen I still see what I submitted in my initial donation, not the updated values, so there might be a problem when submitting the form.

**Review by FranciscoRossoR — APPROVED** [review]
After switching to the right backend branch to test it does work correctly, so sorry about the confusion and well done.

**Pull request merged**
