### PR TITLE
Feature/179-la-salle

### PR DESCRIPTION
**Pull request by claugp06**
The home page for La salle has been created.

### CODE REVIEW

**Review by marnunrey2 — APPROVED** [review]
Perfect, looks really good!

**Review by ivaramlar — CHANGES_REQUESTED** [review]
In the text of  OBRAS LA SALLE, there are some mistakes:
- The text should start in uppercase
- There are some necessary tildes like éstas
- The last paragraph is difficult to understand

**Comment by claugp06** [comment]
> In the text of OBRAS LA SALLE, there are some mistakes:
> 
> * The text should start in uppercase
> * There are some necessary tildes like éstas
> * The last paragraph is difficult to understand

I will have a look to it thnaks. It jus surprised me because I copy the text from the web page

**Review by FelixoGudiel — APPROVED** [review]
Everything is great. Very proffesional work!

**Comment by samrodman** [comment]
I want to point out that it also looks very clean and organised, but just make sure to center the text in the description right under the title, otherwise great job and no big spelling mistakes.

**Review by ivaramlar — APPROVED** [review]
Everything is okay now, well done!

**Pull request merged**
