### PR TITLE
Fix/119-admin-event

### PR DESCRIPTION
**Pull request by samrodman**
I removed the volunteers select from the event screen form, and i tried creating an event and it works. Also was able to fix the issue that when editing an event, it showed the wrong hour in the frontend calendar.

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
Good job, fixing the problems commented.

**Review by claugp06 — CHANGES_REQUESTED** [review]
After, the last information update from the NGO a new option should be added for the creation of an event. An option for recurrent events. Imagine that you want to create an event the same day different weeks, this should be contemplated

**Review by marnunrey2 — APPROVED** [review]
Good job! Just to point something out, when creating or updating an event, the page needs to be refreshed (for updates it takes some time) and it would be a a good improvement for the future not to refresh the page and still the calendar be updated in the moment. Make sure to include what claudia said that the client needs

**Comment by samrodman** [comment]
Now, meetings are shown on the calendar in a different color and you can see the data regarding them. There is a meeting in february and in June. The other fix is that now you have the option of making a recurrent event when creating one. I made sure it is only available for creating and not editing.

**Review by ivaramlar — CHANGES_REQUESTED** [review]
The creation of events works well, but a lot of success messages are shown. Also when you create a new event, it is necessary to reload the page manually. I think that it would be a good option to reload automatically.
Captura de pantalla 2024-03-22 160221

**Review by claugp06 — APPROVED** [review]
Now it works and nice adding that the meetings are seen in the calendar good job with that

**Comment by claugp06** [comment]
> > The creation of events works well, but a lot of success messages are shown. Also when you create a new event, it is necessary to reload the page manually. I think that it would be a good option to reload automatically. Captura de pantalla 2024-03-22 160221
> 
> I'm going to try to fix the refresh aspect, and I tried to fix the multiple messages but with no luck. I'll try a bit more.

Hey,you can maybe use this to the Toast message problem  <ToastContainer limit={3}>

**Review by ivaramlar — APPROVED** [review]
Now everything is okey, well done.

**Review by fracalrod3 — APPROVED** [review]
Everything works and it looks real good, awesome job!

**Pull request merged**
