### PR TITLE
Fix/237 volunteer calendar

### PR DESCRIPTION
**Pull request by manbarjim2**
Now the lessons appear in the volunteers' agenda, you can join them and they appear correctly in the attendance and you can stop belonging to them.
(In order to stop belonging to them, we must wait for Juanlu to add the possibility of deleting lesson-attendance as a volunteer)

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Fix the issues with Codacy and duplication, I had a look and most of them are related with the family Calendar. 
Also, in the legend of th colours used white font instead of white and I am already sign up for an event not message it is shown saying I already belong to it

**Review by Ahydul — CHANGES_REQUESTED** [review]
There is a possible bug. Logging in as javsev @gmail.com. The 12 of june there is an event (Vienen los lunnis) that doesnt change to "Participas" when joining it. 

Also, I noticed that because I tried joining "primer ciclo 1", which works, but make "Vienen los lunnis" "participas" aswell for some reason. The "asistencia" works as expected. It only affects the calendar

**Review by fracalrod3 — COMMENTED** [review]
As Sergio says, there's a bit of a problem with some events, but still a good job overall, just fix that and those Codacy issues

**Review by claugp06 — CHANGES_REQUESTED** [review]
Try to follow the color recommendation given by @Ahydul , also there is somenthing not working with sign up for an event and been update to the attendence part

**Comment by manbarjim2** [comment]
backend is already updated. Juanlu has added the deleting lesson-attendance as a volunteer.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Nice job fixing the duplications. I just one to point out two things:
1. One you are sign up for somenthing it will be nice that the color changes.
2. Also, I am joinning to a class "Jovenes con Horizonte" but it joins me not only to that one but all the different class (also "Infantil" and "Primer Ciclo1"

**Review by Ahydul — DISMISSED** [review]
The errors are fixed and the colors are fine, good job!

**Review by claugp06 — COMMENTED** [review]
I having this issue
image
I tired deleting the local branch several times and still nothing

**Comment by manbarjim2** [comment]
image

I don't get this error

**Review by fracalrod3 — APPROVED** [review]
Everything's working fine

**Review by Ahydul — APPROVED** [review]

**Review by marnunrey2 — APPROVED** [review]
I have checked and everything works fine, good job!

**Pull request merged**
