### PR TITLE
Feature/50-add agenda screen and logos

### PR DESCRIPTION
**Pull request by marnunrey2**

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
It looks good and visual, good job.

**Comment by ivaramlar** [comment]
I am not on the same page as Claudia, the image of the wheel is partly non visible , if you look at the sentence that it has at the right, you can not aprecciate well the words.

**Review by ivaramlar — CHANGES_REQUESTED** [review]
I think that it is necessary change the style in order to be able to see well the logo.

**Comment by marnunrey2** [comment]
The blurry of the picture is made on purpose because it is the style of the homepage that should be followed

**Review by ivaramlar — APPROVED** [review]
All the content is correct.

**Pull request merged**
