### PR TITLE
Feature/5-Navbar login

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Created Login screen.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Use the same container size as the register

**Comment by FranciscoRossoR** [comment]
Changed the flex container to the register style.

**Review by claugp06 — APPROVED** [review]
Looks good now

**Review by samrodman — APPROVED** [review]
looks good, i will accept but the inicie sesion fontSize should match the register later

**Pull request merged**
