### PR TITLE
feat: Admin screen-Account configuration

### PR DESCRIPTION
**Pull request by fracalrod3**

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
To maintain a more cohesive structure make sure your files are js as the rest of them

**Comment by fracalrod3** [comment]
> To maintain a more cohesive structure make sure your files are js as the rest of them

Changed .jsx files to .js as requested

**Review by samrodman — CHANGES_REQUESTED** [review]
in both AdminProfile.js and AdminProfileUpdate there is this import:
import '../../styles/styles.css'

I think you should change it to  '../styles/styles.css' because it gave me  run error otherwise.

The screens look nice but in profile Update, the user should have to repeat the password when updating a new one. Also, in the future the container should be centered, but its okay for now.

**Comment by fracalrod3** [comment]
> in both AdminProfile.js and AdminProfileUpdate there is this import: import '../../styles/styles.css'
> 
> I think you should change it to '../styles/styles.css' because it gave me run error otherwise.
> 
> The screens look nice but in profile Update, the user should have to repeat the password when updating a new one. Also, in the future the container should be centered, but its okay for now.

Changed as requested

**Review by samrodman — APPROVED** [review]
good now, good job

**Review by claugp06 — APPROVED** [review]
Good job now.

**Pull request merged**
