### PR TITLE
Fix/117 educators evaluation

### PR DESCRIPTION
**Pull request by claugp06**
In this PR the evaluation of kids it is done. Now you can evaluate the kid and see the pass evalution grades of it in the button"evaluaciones". This show a summary of the evalutions of the kid until that moment so the educator knows what are the grades.

### CODE REVIEW

**Comment by manbarjim2** [comment]
It does not appear because it has no previous evaluation:

image

image

**Comment by manbarjim2** [comment]
Only the option of 0 appears because it has a previous evaluation.

image

image

**Comment by claugp06** [comment]
> Only the option of 0 appears because it has a previous evaluation.
> 
> image
> 
> image

The thing is that some evaluations are not shown for the children becuase they do not belong to that course that it is been evaluated. The educator have this students but all of them are not in the same class that is why it does not show in some cases the dropdown

**Review by manbarjim2 — APPROVED** [review]
Sorry, everything works as expected, it was my mistake.

**Review by samrodman — APPROVED** [review]
There are a few things we have to tweak, but the basic functionality works. well done!

**Pull request merged**
