### PR TITLE
Fix/238 delete confirmation message

### PR DESCRIPTION
**Pull request by fracalrod3**
1) Log in with administrator credentials.
2) Look up Volunteer or Family Requests, or Suggestions.
3) Click on the "Rechazar" or the trash icon button.
4) There's the pop-up!

### CODE REVIEW

**Comment by fracalrod3** [comment]
> In suggestions the toast message confirmation has been delete it, is not shown and also it stays with the tab of deleting opened.

Sorry, seems I forgot to tell the system to shut the popo-up down, just fixed it, thanks for warning me!

**Review by claugp06 — APPROVED** [review]
Nice, now every delete action has a confirmation message!

**Review by manbarjim2 — APPROVED** [review]
All is working successfully.

**Review by FranciscoRossoR — APPROVED** [review]
Just something to point out, I personally would change "¿Estás seguro que quieres rechazar?" to something like "¿Está seguro de que quiere rechazar?", but still looks and woks as intended, so well done.

**Pull request merged**
