### PR TITLE
Feature/168 family authorizations

### PR DESCRIPTION
**Pull request by FelixoGudiel**
This is my first issue in the frontend! I believe I have fulfilled waht was asked in the Issue description, but since I am new here, I may be susceptible to mistakes that this team are already taking into account. I have taken as reference the mock of figma and followed the expected functionality of the center_Exit_auth.

I am sure that some sections will not comply with the expected work, so please, if you find these problems, tell me ASAP so I can fix them!

As it is right now, when a user enters as a family and goes to the "Autoricaciones" section, two windows will be availible, already signed authorizations and lesson_events of their children that are avalible. From this second view, by specifying the allowed children, the file and the boolean value "are they allowed to go?", a new center_exit_auth will be created.

I hope it works as the general consensus expects it. If not, once again, tell me ASAP so I can correct it!

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Could you give more detail on how to try the funcionality?.My problem is that it appears empty as anything created and I am not sure how to create an entry. Also, could you make a small change? In react the function should start in capital letters and the fucntion of thech the family id you created it is not in capital letters and gives me an error

**Comment by samrodman** [comment]
I created a user a with family role in api/auth/users and activated it but when i log in, in the frontend app I get a 403 error

**Comment by FelixoGudiel** [comment]
Thank you for your feedback! You are right, I tried to fix codacy issues without checking functionality and messed up. Now it works as expected, plus I ahve significantly improved the styles of the section using Artificial Inteligence! Please check it again.

Also, this works with the "develop" version of the backend. Still, there is a fix that im looking into. For now, when you enter into any family (I have used the lucgo@gmail.com for testing) with the password "contraseña" you will recieve an error. This can be mended by either modifying the file NexONG_Backend/nexong/api/Authentication/views.py, to be precise the function `UserApiViewSet` with this code snippet:

```
class UserApiViewSet(ModelViewSet):
    http_method_names = ["get", "put", "delete", "patch"]
    serializer_class = UserSerializer
    queryset = User.objects.all()
    def get_permissions(self):
        if self.request.method == 'GET':
            return [allowAnyGet()]
        return [isAdmin()]
```

Or by using modheader, as claugp06 has told me.

Anyways, tell me if something is not correct!

**Comment by FelixoGudiel** [comment]
I have also added right now the dates for all the sections, I did not realize they were missing in the first pass. Also I have checked that it works with all families!

**Comment by FelixoGudiel** [comment]
Also, the expected use case is:

Login as family (any family!)

Enter in "Autorizaciones"

Check that it works as expected

**Review by samrodman — CHANGES_REQUESTED** [review]
Welcome to frontend, and very nice job fixing the login issue everything works pretty well!
I would like to point out a few imperovements in case you have the time to make this even better.

Would you be able to make the date-time format more legible without the letters T and Z?
Also, the cards are very big with a lot of empty space, if you are able to center the info or make the cards smaller so there can be two columns it would be great.
And finally, when you go to Eventos Disponibles and select a student that is not in that lesson event, for example alberto in excursion a la giralda, you get a prompt error in english, not spanish.

Overall though everything seems to work!

**Comment by FelixoGudiel** [comment]
Thank you for your input! I have changed the date format so that it is more user friendly. About your other requests:

Everything is set to the left in case the name or the description is too long. The current populate has very short descriptions, but the current system will be able to comfortably hold these longer texts.

I, too, have noticed the language change in that case. The error message is the default that comes from the backend. Though it is not official, I am certain that next week there will be an issue in the backend to mend this incongruencies (I will probably take care of it personally) so that the errors outputted are in Spanish. Though not currently, expect the app to output spanish error messages in the near future!

**Review by claugp06 — CHANGES_REQUESTED** [review]
I get several problems when tryying the funcionality:
1. I used the account of the populate and in the console it seems to be working but i get this toast error (I tried to find where it was coming from but nothing): Revise y active su cuenta

2. Also, I tried to log in with an account that I had with the Family role but i enteer to the volunteer screen

**Review by claugp06 — CHANGES_REQUESTED** [review]
Now I can log in and be redirect to the family screen. I would recommend that the navigation after log in it is done to "Niños".
Two small comments to add:
1. The text that appear given the info of the authroizations it is ok but it is no resposive for my screen 
image
Try also to use justify for the align of the text
2.  I tried to dowload the fix and I got this error
image

**Comment by FelixoGudiel** [comment]
Hi! Thank you for your feedback. Adressing your concerns:

I cannot redirect to "Niños" as this page currently does not exist, but im sure that in the future this can be easily corrected.

I have justfied and made more responsive the text.

You cannot download that file because the populate does not include the file itself. It does, however, redirect to the correct download link, so that is expected functionality.

Thank you once again.

**Review by samrodman — APPROVED** [review]

**Review by claugp06 — CHANGES_REQUESTED** [review]
The letters from the authorization should also be resposive in smaller screens (I tried phone and hakf screen) and they are not. The rest looks good

**Review by claugp06 — APPROVED** [review]
After a lot of issues and problems it is working as expect it. The design for the mobile version shpuld be improve but can be done more in advance

**Review by ivaramlar — CHANGES_REQUESTED** [review]
It's necessarily correct a mistake in Register.js, in the line 223 you are calling an existing function onChange={handleAgreedChange}.

**Review by ivaramlar — APPROVED** [review]
Everything work well, now there aren't any problem.

**Review by claugp06 — APPROVED** [review]
Really good job (fixing the log in even it was not your responsability)

**Pull request merged**
