### PR TITLE
Feature/38-pantalla admin Voluntarios y educadores

### PR DESCRIPTION
**Pull request by ivaramlar**
Intento de solucionar error de  codacy.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The screen should contain at the top right side the user log in and the picture.

**Review by claugp06 — CHANGES_REQUESTED** [review]
The styles of each screen it is different.Moreover the whole style of the app it is not respect it. The images are not align the format of the things changes per container.

**Review by fracalrod3 — APPROVED** [review]

**Review by samrodman — APPROVED** [review]
I approve these changes, but must be noted that when the screen changes, the 150x150 image on the people card doesn't stay square I believe.

**Review by manbarjim2 — APPROVED** [review]
Good both screens

**Review by claugp06 — CHANGES_REQUESTED** [review]
It looks good. But you should use here the data from the backend and make sure the volunteers and edcuators are shown correctly from the data of the backend and also that new educators and volunteers can be accept it.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
The creation of educators by the admin is missing.

**Comment by ivaramlar** [comment]
Implemented all the screens that has been requested.

**Review by claugp06 — CHANGES_REQUESTED** [review]
The changes looks good. But only the delete option should be avilable for the admin. The rest looks good even if the documents cannot be taken by the back yet.

**Review by claugp06 — APPROVED** [review]
It works as expected (without the uploading witht the documents from the back). This can be done when it is finished by the back but keep it in mind so it is not forgotten.

**Review by manbarjim2 — APPROVED** [review]
Everything seems to be correct.

**Pull request merged**
