### PR TITLE
Fix/148-Association information

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Added descriptions to all boxes in Association screen

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The information include it it is good but I have a suggestion if you could make the change it would be really nice. Could you try that all the button in blue appear at the same height so it gives a more clean view of the screen?

**Comment by FranciscoRossoR** [comment]
Changed HomepageContainer so buttons use flex properties to appear on the bottom left.

**Review by claugp06 — APPROVED** [review]
Nicely done, now the views looks better and more organised. Good job!

**Review by Ahydul — APPROVED** [review]
It looks good, nice job!

**Pull request merged**
