### PR TITLE
Feature/81-Navbar suggestions

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Created the Suggestions screen with a form.

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
It works as expected

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
Punctual donations work fine, but I can't make recurring donations:

image

**Comment by FranciscoRossoR** [comment]
> Punctual donations work fine, but I can't make recurring donations:
> 
> image

@fracalrod3 there might have been a little confusion, this task is about the Suggestions screen and not the Donations one.

**Review by fracalrod3 — APPROVED** [review]
Yep, sorry

**Pull request merged**
