### PR TITLE
Fix/162 - volunteers calendar

### PR DESCRIPTION
**Pull request by manbarjim2**
Volunteers can register for events, lesson events (those belonging to a specific class), and classes they can attend.

### CODE REVIEW

**Review by claugp06 — COMMENTED** [review]
Could you provide more info how to try this funcionality?. Right now the creation of class and events from the frontend it is been fixed because with the last backend changes it is not working

**Review by marnunrey2 — APPROVED** [review]
Everything works fine. I have created a volunteer and logged in with its credentials and I have registered for the "excursion a la giralda". When registering it changes it's color and if I try to join again it shows that I'm already enrolled. Good job! remember to update the branch before merging

**Comment by manbarjim2** [comment]
> Could you provide more info how to try this funcionality?. Right now the creation of class and events from the frontend it is been fixed because with the last backend changes it is not working

In this functionality volunteer can join a lesson, just like volunteer can join an event. All events and lessons that exist after the current date appear on the calendar and you select the one you want to join.

**Review by claugp06 — APPROVED** [review]
Thanks, for the aclaration now I have been able to try and works as expect it

**Pull request merged**
