### PR TITLE
Fix/234 family

### PR DESCRIPTION
**Pull request by Ahydul**
- Removed “Niños” from family menu.
- Fixed calendar activity related errors.
- Added color to differentiate between the activity types and added a legend to understand the colors.

To test go to http://localhost:3000/familia/calendario as a family user

### CODE REVIEW

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
I have created a family and a student. I have also created a lesson with this student (so that it appears at the fimily calendar). But when going to /familia/calendario, I get the following error:
```
Cannot read properties of undefined (reading 'weekday')
TypeError: Cannot read properties of undefined (reading 'weekday')
```

Also, I think it would be better if you add the legend of the calendar above it and not below

**Review by marnunrey2 — APPROVED** [review]
My bad, it seems to work perfectly fine, good job!

**Review by FelixoGudiel — APPROVED** [review]
Nice job!

**Review by claugp06 — APPROVED** [review]
Nice job!

**Pull request merged**
