### PR TITLE
Fix/146-History-Homepage

### PR DESCRIPTION
**Pull request by samrodman**
The History page of the homepage was missing the actual description from the real website. I added as best I could and would appreciate feedback on how it looks, thank you.

### CODE REVIEW

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
I think you missunderstood the Intro component. The intro component is only for displaying the background photo, the title of the page and maybe some little description. In this case, the description should be after the Intro component and before the image. Also, I don't see the utility of creating a new component here because it's some information that it's not going to be used in any other page. I would just write all the text in some <p> before the image and I would improve the image quality of the table and try to minimize it a bit so it does not cover the whole screen

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
I feel like the content's alright but it feels more like a timetable than anything, it's also fairly difficult to see everything because of the image's quality.

**Comment by samrodman** [comment]
I applied the suggested changes and some of my own, I hope it's better now! thank you

**Review by claugp06 — CHANGES_REQUESTED** [review]
I think it looks good and how the info it is shown but the image in the side it is a bit small.Could you make it bigger?

**Review by marnunrey2 — APPROVED** [review]
Looks good now, I agree with claudia maybe a bit bigger the image but so far pretty good.

**Review by fracalrod3 — APPROVED** [review]
Definitely looks a lot better, still a bit blurry but a lot more legible

**Review by claugp06 — APPROVED** [review]
The image now looks bigger and it makes the screen more legible. Great job!

**Pull request merged**
