### PR TITLE
Feature/120  admin volunteers docs

### PR DESCRIPTION
**Pull request by ivaramlar**
Now it is possible to download a file, to do it, it is necessary to follow the next steps:
1- Create a new volunteer object in the API with status="PENDIENTE" and correct files.
2- Create a new user with type volunteer and establish the new volunteer created before.
3- Initiate the app and login like an admin, go to volunteer request and click on the bottom descargar.

Only the enrollment document is going to be downloaded because I haven't been able to implement the functionality to download several of them. I have been more of an hour fighting ChatGPT, but it doesn't help at all.

### CODE REVIEW

**Review by claugp06 — COMMENTED** [review]
I followed the steps and created a volunteer in the Api but it does not appear in "Solicitudes" maybe I am doing somenthing wrong but I cannot be sure

**Comment by ivaramlar** [comment]
> I followed the steps and created a volunteer in the Api but it does not appear in "Solicitudes" maybe I am doing somenthing wrong but I cannot be sure

Have you created a user and established the volunteer id ?  I have done that and i can see the new user in request.

**Review by claugp06 — CHANGES_REQUESTED** [review]
My bad i did not put the Id sorry. I have a few things to point out.
- It will be nice if a toast message it shown when a volunteer it is accepted or reject it. 
- As it is said the docs are empty why is that? The docs parts it has been done my the backend already
- I know you comment it that only you are able to download the enrollment but it should be all the documents download. If you need help , ask the frontend people they might have some idea

**Review by marnunrey2 — COMMENTED** [review]
I have tested it and it works but, as you said, it's only downloading the enrollment document. Have you though of trying that in the descargarDocumento constant try to get every document of the volunteer (check if the volunteer is under 18 to download also the minor authorization and the scanned authorizer id) and with those files create a zip and assign the enlaceDescarga.href and enlaceDescarga.download to the zip created?

**Comment by ivaramlar** [comment]
The issue is going to be done in the week number 10, it needs that the funtionality stay implemented in the back before.

**Comment by claugp06** [comment]
> The issue is going to be done in the week number 10, it needs that the funtionality stay implemented in the back before.

Sounds good, could you have in account the following (becuase you are already working on volunteers and you have been working more over it and have more idea of the code) that volunteers can be edit by the admin

**Comment by ivaramlar** [comment]
Now, it is possible to download a zip with all the files from a volunteer. To do it, it is necessary to follow all the steps that I put in the first comment.

**Review by claugp06 — CHANGES_REQUESTED** [review]
I have the last version of develop of the back and when I press download to check the file I get this error
image

**Comment by ivaramlar** [comment]
> I have the last version of develop of the back and when I press download to check the file I get this error image

Please follow the instructions, you are trying to download the files from a user loaded from the API instead of a user created by you.

**Review by marnunrey2 — APPROVED** [review]
Good, it works as expected!

**Review by FelixoGudiel — APPROVED** [review]
Works as expected.Good job!

**Pull request merged**
