### PR TITLE
Fix: feedback pilot users

### PR DESCRIPTION
**Pull request by claugp06**
The errors regarding the home page mentioned by the pilot users have been solved. For that:
1. In "entidades colaboradoras" the links have been change for the donwload image because a possible error of why not been showed is that the link is not allowed by cors headers
2. The hsitory picture has been changed
3. The text of "club de verano" has been centered

### CODE REVIEW

**Review by MartaInes — DISMISSED** [review]
The changes were done successfully. Good job! 
(Let's hope that the images are still visible when doing the deploy)

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Create meaningfull and short names for the images, otherwise you can get errors like the one I got that it deleted this file: '../../logo/ColaboratorsEntities/Logo_de_la_Consejeria_de_Inclusion_Social_Juventud_Familias_e_Igualdad_de_la_Junta_de_Andalucia.png' because the name was too long

**Comment by claugp06** [comment]
> Create meaningfull and short names for the images, otherwise you can get errors like the one I got that it deleted this file: '../../logo/ColaboratorsEntities/Logo_de_la_Consejeria_de_Inclusion_Social_Juventud_Familias_e_Igualdad_de_la_Junta_de_Andalucia.png' because the name was too long

I did not think of that but it is a quick fix thanks for the tip (I saved the pcitures with the same name as they were download it)

**Review by marnunrey2 — APPROVED** [review]
Thanks, nice job!

**Review by Ahydul — APPROVED** [review]
Looks good

**Pull request merged**
