### PR TITLE
Fix/190 delete roles

### PR DESCRIPTION
**Pull request by marnunrey2**
In this PR, I have implemented the deletions, acceptance and declines for each role in admin with the new backend (it deletes the role and automatically deletes its user). Steps to follow:

1. Log in as admin
2. Go to 'Voluntarios' and delete one of them (in api/volunteer and in api/user this volunteer will disappear)
3. Go to 'Voluntarios' > 'Solicitudes': if you accept the volunteer, the status for the volunteer in api/volunteer will change to ACEPTADO and if you decline it, the status will be RECHAZADO (Make sure you have volunteers with status PENDIENTE at the begginning. You can try many times by doing a put on api/volunteer/id changing the status to PENDIENTE)
4. Go to 'Educadores' and delete one of them (in api/educator and in api/user this educator will disappear)
5. Go to 'Socios' and delete one of them (in api/partner and in api/user this partner will disappear)
6. Go to 'Familias', here the delete is not implemented because the ong has not asked us to be able to delete a family. 
7. Go to 'Familias' > 'Solicitudes': if you accept the family kid, the status for the student in api/student will change to ACEPTADO and if you decline it, the status will be RECHAZADO (Make sure you have students with status PENDIENTE at the begginning. You can try many times by doing a put on api/volunteer/id changing the status to PENDIENTE)

Also, here is implemented the possibility for the user to delete all his/her data. Steps to follow:
1. Log in as a user with any kind of role (except ADMIN)
2. Got to profile and a red button to delete info will appear at the bottom. When clicking, a dialog will appear asking for confirmation and when confirming, the page will be redirected to the homepage. (you can see in api/user and in api/role that the user has been removed)

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
I tried trying your funcionality but I cannot do it because I get this error
image
I have the last version of the backend and I have log in as admin.

**Review by claugp06 — APPROVED** [review]
I could finally check it and it work but I have a question: it is not giving 401 error becuase modheader it is been used, are you sure it will work without it?

**Comment by marnunrey2** [comment]
> I could finally check it and it work but I have a question: it is not giving 401 error becuase modheader it is been used, are you sure it will work without it?

I just though the same thing and asked the backend team for some information. I actually don't think so, but I'm waiting for the register without modheader pr to be on develop and check it myself. Do not merge this pr before I can check it.

**Review by ivaramlar — APPROVED** [review]
Everything is okay, I have been able to remove my data and to manage the data of the users as an admin, well done!

**Review by claugp06 — COMMENTED** [review]
It seems everything it is working and goof job with the conflicts

**Review by claugp06 — APPROVED** [review]
It seems everything it is working and goof job with the conflicts

**Pull request merged**
