### PR TITLE
Fix/214-toast-error

### PR DESCRIPTION
**Pull request by FelixoGudiel**
I have systematically inspected each error that can be outputted and made sure they are in spanish. I have translated those that dont. I have also checked the feedback from the pilot users to find these errors. Also the google login button has been removed and the text of the toast error has been overriden to black always, to also address the "white on white" text feedback.

If you find any incongruence, do tell me!

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
In the admin screen in documentation I would say to add a toast message for the type of document so that only PDF it is allow (now it allows to upload an image for example).
Also in suggestion the toast message for delating the suggestion the options are in English.
I don't know what you think but a confirmation message before doing a delte could be a good idea
Apart from that everything seems correct and all the toast messages have been translated it

**Comment by FelixoGudiel** [comment]
Though I agree that adding a second screen before deleting any entity would be a nice addition, this would be a very long task to complete, as there are many deletable objects. However, I have fixed your other request and also corrected suggestions so that even anonymous users can send suggestions.

**Review by claugp06 — DISMISSED** [review]
I think for now it is ok how it is done. Now it is working and I think all the toast messages are shown as expected

**Review by FranciscoRossoR — CHANGES_REQUESTED** [review]
There's still a little typo when submitting a punctual donation with a name or a surname longer than 75 characters:
```Indica un nombre, no debe superar 75 caráteres```
The word "caráteres" does not exist in Spanish (as far as I know). Also, since we're changing that message, it would be nice to keep the "usted" treatment consistent (in the same page, other messages say "Introduzca", for example, but this ones say "Indica").

**Comment by FelixoGudiel** [comment]
You are right, now it is fixed! Thank you.

**Comment by FranciscoRossoR** [comment]
A little more thing, just realized the message for name and surname is the same.

**Comment by FelixoGudiel** [comment]
Thank you again!

**Review by FranciscoRossoR — DISMISSED** [review]
Everything looks good, thanks for your patience with the little mistakes and good job.

**Review by claugp06 — DISMISSED** [review]
Looks good now and thanks @FranciscoRossoR for your sharp eye noticing small things

**Review by marnunrey2 — DISMISSED** [review]
Good job with the toast messages. Be careful with the merge conflicts

**Review by marnunrey2 — APPROVED** [review]
Good job!

**Review by FranciscoRossoR — APPROVED** [review]
Still works correctly after the merge, well done.

**Pull request merged**
