### PR TITLE
Fix/151 transparencies

### PR DESCRIPTION
**Pull request by MartaInes**
In this PR is added the option in the Admin page to add documents to the homepage transparency table. 

To see that it works you can upload a document from admin/documentos and go to the homepage transparency screen to see that it was correctly added to the table under the column of its docType. 

Right now there is only one document in the populate, so if you don't add anything it should only appear that one.

### CODE REVIEW

**Review by claugp06 — APPROVED** [review]
Great job Marta!. I added a new doc and it appears on the table. I will talk with the backend so the database they use for the deploy has te documents needed

**Review by marnunrey2 — COMMENTED** [review]
I tried the funtionality and works partially. For some reason, when adding a new file, I select as DocType "Documentos Institucionales", but appears on the "Otros documentos" column. Also, make sure that the parameter "selected" on the Layout is Documentos and make sure that in the menu when clicking documentos, it stays shaded

**Comment by MartaInes** [comment]
> I tried the funtionality and works partially. For some reason, when adding a new file, I select as DocType "Documentos Institucionales", but appears on the "Otros documentos" column. Also, make sure that the parameter "selected" on the Layout is Documentos and make sure that in the menu when clicking documentos, it stays shaded

I changed the hover, so now it should be correct. About the document types, I tried it, and it works for me.

**Review by marnunrey2 — APPROVED** [review]
Everything works perfect, good job!

**Comment by samrodman** [comment]
Hi! I would also like to add that it works very well, as intended. I have a question though, when you upload a document as admin, in 'Fecha' input, is it supposed to be the date of when you do the upload? Because it allows to select a past date, just letting you know.

**Review by samrodman — APPROVED** [review]

**Pull request merged**
