### PR TITLE
Feature/61 landing page

### PR DESCRIPTION
**Pull request by fracalrod3**
Remade Landing Page according to Team Lead's requests and changing AdminProfile and AdminProfileUpdate routes to Spanish

### CODE REVIEW

**Comment by fracalrod3** [comment]
New necessary informative text pending

**Review by claugp06 — CHANGES_REQUESTED** [review]
The landing page should be independent from the front-end and should be already deploy

**Review by claugp06 — APPROVED** [review]
The landing page aspesct improved a lot and it is working and responsive.

**Review by FranciscoRossoR — APPROVED** [review]
Well done.

**Pull request closed without merging**
