### PR TITLE
Fix/118 admin partners

### PR DESCRIPTION
**Pull request by ivaramlar**
Solved the problems related to the views of partners, volunteers and educator. Also i have implemented the corretion of admin assembly.

### CODE REVIEW

**Review by marnunrey2 — APPROVED** [review]
Everything looks perfect and it's working. Nice job!

**Review by claugp06 — CHANGES_REQUESTED** [review]
The changes here work as expected but when a meeting it is creat a toast message showing it was successful should be shown.

**Comment by ivaramlar** [comment]
Now, a success message is shown when a new assembly is created, and a error messagge when there is a mistake.

**Review by claugp06 — APPROVED** [review]
Nice work, now the errors are handle in a nice way!

**Pull request merged**
