### PR TITLE
Feature/171 registration of families

### PR DESCRIPTION
**Pull request by manbarjim2**
Once a user has registered and has the family role, they are redirected to the forms corresponding to the family. There are two forms, one with the children's data and the other with the family's data.

### CODE REVIEW

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
I manage to do the registration of the user and the family was created on the api but when I try to login it says: "No active account found with the given credentials". but I checked and the user is enabled, so I think there's something wrong with your code. After checking I think you should take a look at how the voluntario login is done and try to do something similar

**Review by claugp06 — CHANGES_REQUESTED** [review]
I tried again and still the same error
image

**Comment by manbarjim2** [comment]
There are two issues for this branch related to backend:

1. Family does not have a status to go from WAITING to ACCEPTED.

2. And also when you register as a family, it automatically assigns you a familyId so it is never null.

**Comment by claugp06** [comment]
> There are two issues for this branch related to backend:
> 
> 1. Family does not have a status to go from WAITING to ACCEPTED.
> 2. And also when you register as a family, it automatically assigns you a familyId so it is never null.

The registration of a family it is always accepted the NGO does not accepted them, what they accept is the kids not the family itself, whay you need to do is to created the form to complete the date needed for been a family and thats all

**Comment by manbarjim2** [comment]
> > There are two issues for this branch related to backend:
> > 
> > 1. Family does not have a status to go from WAITING to ACCEPTED.
> > 2. And also when you register as a family, it automatically assigns you a familyId so it is never null.
> 
> The registration of a family it is always accepted the NGO does not accepted them, what they accept is the kids not the family itself, whay you need to do is to created the form to complete the date needed for been a family and thats all

And also the form to register as a child, right?

**Comment by claugp06** [comment]
> > > There are two issues for this branch related to backend:
> > > 
> > > 1. Family does not have a status to go from WAITING to ACCEPTED.
> > > 2. And also when you register as a family, it automatically assigns you a familyId so it is never null.
> > 
> > 
> > The registration of a family it is always accepted the NGO does not accepted them, what they accept is the kids not the family itself, whay you need to do is to created the form to complete the date needed for been a family and thats all
> 
> And also the form to register as a child, right?

That's already done in the pull request of @Ahydul in the kids part I think

**Comment by manbarjim2** [comment]
> > > > There are two issues for this branch related to backend:
> > > > 
> > > > 1. Family does not have a status to go from WAITING to ACCEPTED.
> > > > 2. And also when you register as a family, it automatically assigns you a familyId so it is never null.
> > > 
> > > 
> > > The registration of a family it is always accepted the NGO does not accepted them, what they accept is the kids not the family itself, whay you need to do is to created the form to complete the date needed for been a family and thats all
> > 
> > 
> > And also the form to register as a child, right?
> 
> That's already done in the pull request of @Ahydul in the kids part I think

I saw it, in this issue we were also doing it but I just deleted it to leave only his.

**Comment by claugp06** [comment]
> > > > > There are two issues for this branch related to backend:
> > > > > 
> > > > > 1. Family does not have a status to go from WAITING to ACCEPTED.
> > > > > 2. And also when you register as a family, it automatically assigns you a familyId so it is never null.
> > > > 
> > > > 
> > > > The registration of a family it is always accepted the NGO does not accepted them, what they accept is the kids not the family itself, whay you need to do is to created the form to complete the date needed for been a family and thats all
> > > 
> > > 
> > > And also the form to register as a child, right?
> > 
> > 
> > That's already done in the pull request of @Ahydul in the kids part I think
> 
> I saw it, in this issue we were also doing it but I just deleted it to leave only his.

The idea of this issue was to create the form for the families maybe was my bad

**Review by claugp06 — COMMENTED** [review]
Please fix the conflicts errors that appears

**Review by claugp06 — CHANGES_REQUESTED** [review]
I was able to do the register and the form needed to complete the family registration it is shown (maybe add a tittle or some info saying that some info it is needed it) but when I press send it gives this error 
image
Have you include the tokens?

**Review by claugp06 — CHANGES_REQUESTED** [review]
It works now (well done) but just two small details:
1. The password should not be needed it in that form
2. I have this alert message that appear after the success 
image
If you want to show some error/sucess message use toast please

**Review by claugp06 — CHANGES_REQUESTED** [review]
Add a tittle to the form ann instead of "apellido 1" use "primer apellido". Also, I introduced the data and press send and I was redirect but given an error message

**Review by claugp06 — CHANGES_REQUESTED** [review]
A toast message of succes it not shown, also consider using a whole new screen without headers and side menu for showing the register form of family and once it is done redirect to "niños" insteas of profile

**Review by claugp06 — APPROVED** [review]
Everything seems good now

**Review by marnunrey2 — APPROVED** [review]
Great job, it works!

**Review by marnunrey2 — APPROVED** [review]
Still works, well done!

**Review by claugp06 — APPROVED** [review]
It seems everthing it is ok and good job with the conflicts

**Pull request merged**
