### PR TITLE
Feature/166 privacy policy

### PR DESCRIPTION
**Pull request by claugp06**
The privacy terms has been added in the register. Now if you access to the register and press "términos y condiciones" a dialog will be open with the points of it. The text included has been used from the one given by the backend api created for this part.

### CODE REVIEW

**Review by ivaramlar — APPROVED** [review]
All is correct except a little mistake in the first paragraph, you have put "Términos y Condiciones de Uso." It is necessary to change to "Términos y Condiciones de Uso:"

**Review by manbarjim2 — APPROVED** [review]
Done correctly, easy to use. Thanks for your good work.

**Comment by claugp06** [comment]
> All is correct except a little mistake in the first paragraph, you have put "Términos y Condiciones de Uso." It is necessary to change to "Términos y Condiciones de Uso:"

I also noticed it, the thing is that the text is coming from the API endpoint so to change it the text should be correct there (I could do itmanually but it is not the best approach)

**Review by marnunrey2 — APPROVED** [review]
Looks good!

**Review by ivaramlar — APPROVED** [review]
All work well, well done!

**Pull request merged**
