### PR TITLE
Fix/262 info

### PR DESCRIPTION
**Pull request by marnunrey2**
In this PR, I have added info for actors in admin page and added the event info when the volunteer clicks on the event.
To test it:
- Log in as admin and see Voluntarios, Voluntarios > Solicitudes, Socios, Educadores, Familia and Familia > Solicitudes
- Log in as volunteer and click on an event in the calendar

### CODE REVIEW

**Review by claugp06 — COMMENTED** [review]
Everything looks good and now the blue cards do not look so empty but I have a doubt: when I tried to download some file it does not work and I was wondering if this was because they are from the populate and the file does not exit

**Comment by marnunrey2** [comment]
> Everything looks good and now the blue cards do not look so empty but I have a doubt: when I tried to download some file it does not work and I was wondering if this was because they are from the populate and the file does not exit

yes, forgot to mention. The buttons for downloading won't work with the people from the populate of the backend. If you want to test it, you'll need to create an actor of that role and then you can download the file

**Review by claugp06 — APPROVED** [review]
Oki,thanks for letting it know and I could check it and it works

**Review by Ahydul — APPROVED** [review]
Good job!

**Review by FelixoGudiel — APPROVED** [review]
Nice job!

**Pull request merged**
