### PR TITLE
Fix/145 about us

### PR DESCRIPTION
**Pull request by marnunrey2**
Youtube video added and dossier dismissed after NGOs request.

### CODE REVIEW

**Review by claugp06 — DISMISSED** [review]
It looks nice and well done even it is a bit tought to read about the NGO refusal

**Review by FelixoGudiel — COMMENTED** [review]
I would change the first line from "Manos Abiertas con Norte somos una ONG de La Salle en Sevilla desde 1995, centrados en educar a niños y jóvenes vulnerables mediante proyectos socioeducativos." to "Somos Manos Abiertas con Norte, una ONG de La Salle en Sevilla desde 1995, centrados en educar a niños y jóvenes vulnerables mediante proyectos socioeducativos.", to me it sounds better, though maybe the ngo wants it that way.

**Review by claugp06 — DISMISSED** [review]
I missed that little typo but now it fixed and should be fine

**Review by MartaInes — DISMISSED** [review]
It looks good. Good job!

**Review by FelixoGudiel — APPROVED** [review]
Nice wok!

**Review by MartaInes — APPROVED** [review]
Yeah, it's better after the change.

**Pull request merged**
