### PR TITLE
Feature/154-log in register token

### PR DESCRIPTION
**Pull request by claugp06**
In this PR the changes for creating the log in as an authenticated user have been implement it. In order to be able to check its performance you have to following steps:
1. Create a new user using the register (you have to use a real email for it) and activate the account by following the link from the mail and pressing the post button. After this the account will be active.
2. Go to the admin screen of django and check that the user has a role assign (not family becuase the screens are not implemented yet)
3. Once you checked it has a role assign then try to log in and the corresponding screen should appear.
Keep in mind that right now after doing the register for family or volunteer you will be redirect to their register form pages (which are not yet done). When this part it is functional then the part of checking the role from the admin screen would not be neccesary

### CODE REVIEW

**Comment by samrodman** [comment]
Do we have to register in the register screen or on the api?

**Comment by claugp06** [comment]
Using the register form

El 27 mar 2024 17:54, samrodman ***@***.***> escribió:

Do we have to register in the register screen or on the api?

**Review by ivaramlar — APPROVED** [review]
Everything works well, I have done all the steps that you have indicated and it looks fine. ¡Well done!

**Review by marnunrey2 — APPROVED** [review]
At first I have troubles trying to register bt after fixing some self problems I manage to do the register and log in totally fine. I get the email and I manage to activate the account and can be seen clearly on the /api/user in the is_enabled attribute. Just to point out, I created a volunteer profile and in the api appears FAMILY as a role and null in volunteers. Guess that's a backend problem. When log in, the volunteers profile appears. Great job!

**Comment by claugp06** [comment]
> At first I have troubles trying to register bt after fixing some self problems I manage to do the register and log in totally fine. I get the email and I manage to activate the account and can be seen clearly on the /api/user in the is_enabled attribute. Just to point out, I created a volunteer profile and in the api appears FAMILY as a role and null in volunteers. Guess that's a backend problem. When log in, the volunteers profile appears. Great job!

I noticed that but I think it is related with somenthing with the backend. I will have a look and see why it could be. Thanks!

**Review by fracalrod3 — APPROVED** [review]
Everything seems to work just fine, awesome job!

**Pull request merged**
