### PR TITLE
Feature/90-VolunteersAgenda

### PR DESCRIPTION
**Pull request by manbarjim2**
The agenda for the Volunteer and the posibility of  join if they can go

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
It should not exist the possibility to add to a past event like now. Also, I tried to join to the event of June and it gives an error:
image
A message to handle the errors, should be added also so the user know why it is not working if he/she tries to join an event.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Looks good, now I can join to an event but it would be nice that once th user has joined a message it is shown so it is know that the registration for the event worked.Also,have you checked that it is not allowed that the same volunteer cannot join 2 times?

**Comment by manbarjim2** [comment]
image

image

**Review by claugp06 — APPROVED** [review]
Seems as everything it is working.Nice job!

**Review by MartaInes — APPROVED** [review]
Everything works as expected, good job!

**Review by FranciscoRossoR — APPROVED** [review]
Looks good, well done.

**Pull request merged**
