### PR TITLE
Feature/83 86 universal profile and update

### PR DESCRIPTION
**Pull request by fracalrod3**
Profile and update Profile as components: educator, volunteer and admin work correctly

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Instead of using alear use toastify as mentioned before. Also, if you put some data in the incorrect format (I put the phone that it is not correct) not error is given
image

**Review by samrodman — COMMENTED** [review]
I agree with claudia, we need to see some validations when updating the profiles so the user can see the error. This can be done with toastify so you show the 400 error detailed.

**Review by claugp06 — APPROVED** [review]
Now the errors are handled good job

**Review by samrodman — APPROVED** [review]
Well done!

**Pull request merged**
