### PR TITLE
fix: update student acceptance to backend changes

### PR DESCRIPTION
**Pull request by Ahydul**
Added to the patch of student when accepting a student as admin the acceptance_date.

### CODE REVIEW

**Comment by FelixoGudiel** [comment]
Please merge the latest changes form develop and indicate the process to check this feature

**Comment by Ahydul** [comment]
> Please merge the latest changes form develop and indicate the process to check this feature

As a family user create a student in /familia/niños/registro
As an admin user accept the user in "/admin/familias/solicitudes"
In the backend check that the student is accepted and the accepted date is the actual date

**Review by claugp06 — COMMENTED** [review]
It seems working but I have a doubdt. If the accepted_date reaches a year does that student automatically stop being enroll? Because if not, it should be done like that

**Comment by Ahydul** [comment]
> It seems working but I have a doubdt. If the accepted_date reaches a year does that student automatically stop being enroll? Because if not, it should be done like that

That is managed in the backend and it's supposed to work like that

**Comment by claugp06** [comment]
> > It seems working but I have a doubdt. If the accepted_date reaches a year does that student automatically stop being enroll? Because if not, it should be done like that
> 
> That is managed in the backend and it's supposed to work like that

And in the backend once the time is exceeded it is delete it?

**Comment by Ahydul** [comment]
> And in the backend once the time is exceeded it is delete it?

Like I said, that is how it is supposed to work. I've obviously not tested it because that was not my job. If the backend was merged into develop then I suppose that it does indeed work.

**Review by claugp06 — APPROVED** [review]
Everything works as expected

**Review by FelixoGudiel — APPROVED** [review]
good job

**Pull request merged**
