### PR TITLE
Feature/115 log out button header

### PR DESCRIPTION
**Pull request by fracalrod3**
Now when logging in, you don't have to hover around and click the button, you can just press enter and it'll all work out!

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The log out button shoud be in the header not in the side menu. INstead of red use the blue that has been used in the project

**Comment by fracalrod3** [comment]
In this Pr's branch I'll do both the button and everything related to issue #130. Regarding that issue, the avatar isn't shown correctly since it's impossible to access any user's avatar since they're not online nor accessible through the API for now, so it won't load for the moment

**Review by samrodman — APPROVED** [review]
good job, I see it's working. For some reason though i see the proportions of the button a little odd, but it could be because of a styles update
image

a further improvement would be a pop up saying '¿Estás seguro de que quiere cerrar sesión?' but well done!

**Review by ivaramlar — APPROVED** [review]
The button looks great, work great and is responsive, well done.

**Pull request merged**
