### PR TITLE
Feat/57-AboutUs, history and Mision, Overviews and Values screens

### PR DESCRIPTION
**Pull request by manbarjim2**
Creation of the corresponding screens for the asociations dropdown more specifically: About us/ History/ Mision, Overview and values.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Good first approach but it would be better if you follow the same idea as the home page or general screen for activities: include some pictures and makeit more visually. Also the general tab for asociations it is not done if you could create it.

**Review by claugp06 — CHANGES_REQUESTED** [review]
The screen it is not looking as the other ones and it is not really visual. Also  the containers and the info does not fit

**Review by claugp06 — CHANGES_REQUESTED** [review]
There is some clones in the code you should create as component the repeated code

**Review by claugp06 — APPROVED** [review]
Looks good for now, the pictures and content may change when we get the data from the NGO

**Review by FranciscoRossoR — APPROVED** [review]
Looks good, well done.

**Review by samrodman — APPROVED** [review]
it's alright to me, well done

**Review by claugp06 — APPROVED** [review]
Nice done resolving the conflicts

**Pull request merged**
