### PR TITLE
Feature/170 family calendars

### PR DESCRIPTION
**Pull request by manbarjim2**
In this PR, I have implemented the family calendar. 
To try it, follow these steps:

1. Make sure that you are running the latest version of branch develop of the backend and that you have a user admin on the api you can access with (If not follow the steps using the auth/users) and
2. If you cannot use a family already created, you must create a family and a student who is a member of the same family and join this student to some event or lesson event
3. Sign in as this family member
4. You will be able to see the events and lesson events that your student family attends

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The family should be able to also see the lessons of their kids

**Review by claugp06 — COMMENTED** [review]
Please, merge the branch with develop for the last changes because right now I cannot try your implementation

**Review by claugp06 — CHANGES_REQUESTED** [review]
I am not using modheader when trying your funcionality and I get this error
image
Also, look the rest of the calendars implemented it the stylr looks better

**Comment by manbarjim2** [comment]
I use the same style of the rest calendar implemented.

**Review by ivaramlar — COMMENTED** [review]
Captura de pantalla 2024-04-18 130959
I have found a bug, when i have pressed Mandar autorización, this error came, after pressing three times more, everything was correct and work well. 
Also, i have the same problem with the calendar, nothing is shown.

**Comment by manbarjim2** [comment]
> Captura de pantalla 2024-04-18 130959 I have found a bug, when i have pressed Mandar autorización, this error came, after pressing three times more, everything was correct and work well. Also, i have the same problem with the calendar, nothing is shown.

Authorizations are not part of this issue

**Comment by manbarjim2** [comment]
> Please look how the other calendar are implemented for the style it looks different and secondly I am using a family of the populate "[annanna@gmail.com](mailto:annanna@gmail.com)" which has some kids that are in some lessons but nothing it is shown in the calendar should be somenthing shown?

image
I logged in with that email and the lessons to which your son belongs appear

**Review by claugp06 — CHANGES_REQUESTED** [review]
I do not see anything still
image

Also the next back and month name should be in Spanish

**Comment by manbarjim2** [comment]
> I do not see anything still image
> 
> Also the next back and month name should be in Spanish

Can you explain to me step by step what you do to check it?
Calendar, which is what we use to create calendars, comes in English, I will try to change the language.

**Comment by claugp06** [comment]
> > I do not see anything still image
> > Also the next back and month name should be in Spanish
> 
> Can you explain to me step by step what you do to check it? Calendar, which is what we use to create calendars, comes in English, I will try to change the language.

I have log in as the indicated user and I have seen that their kids are enroll in some classes so it should appear on the calendar and it does not, it show empty maybe it is because the id it is not check correcctly or the id on the localstorage it is not the supposed one

**Review by claugp06 — CHANGES_REQUESTED** [review]
Now it works and shows the events realted to the family but it will be nice that when pressing them more info would be shown such as the hours they are happening

**Review by FranciscoRossoR — DISMISSED** [review]
The feature seems to work correctly.

**Review by claugp06 — COMMENTED** [review]
I have a few doubts:
1.Only the classes appears or also the events of the specific kid
2. It is the calendar filter by the kids of the family or not? I am wondering because I log in with a different family 
3. If somenthing apart of classes are shown like events or lesson events might be nice to use some color to differenciate it

**Comment by manbarjim2** [comment]
> I have a few doubts: 1.Only the classes appears or also the events of the specific kid 2. It is the calendar filter by the kids of the family or not? I am wondering because I log in with a different family 3. If somenthing apart of classes are shown like events or lesson events might be nice to use some color to differenciate it

1.
Events and lessons events also appear.

2.
Yes, the calendar is filtered by children in the family.

3.
I will make the change to differentiate by color.

**Comment by manbarjim2** [comment]
image

**Review by claugp06 — CHANGES_REQUESTED** [review]
When showing the details of the events/class/lesson event it would be nice that tittle represents it also I do not understand how the time and dates are shown because it says like a start time and hour and the end date nd hour is diferent

**Comment by manbarjim2** [comment]
> When showing the details of the events/class/lesson event it would be nice that tittle represents it also I do not understand how the time and dates are shown because it says like a start time and hour and the end date nd hour is diferent

It wouldn't make sense for the start time and date to be the same as the end date, right?

**Comment by claugp06** [comment]
> > When showing the details of the events/class/lesson event it would be nice that tittle represents it also I do not understand how the time and dates are shown because it says like a start time and hour and the end date nd hour is diferent
> 
> It wouldn't make sense for the start time and date to be the same as the end date, right?

If it represents a class it would make more sens to show the date and time like from 12 until 13

**Review by ivaramlar — DISMISSED** [review]
Now the calendar works well, and I am able to see the events, well done!

**Review by claugp06 — CHANGES_REQUESTED** [review]
Instead of always use as title "detalles del evento" depending on what it is, the tittle should be different

**Review by claugp06 — CHANGES_REQUESTED** [review]
image
Why the date of that class it is incorrect? comes like that from the popualte?

**Comment by manbarjim2** [comment]
image
The lessons do not specify the hours

image

**Comment by claugp06** [comment]
> image The lessons do not specify the hours
> 
> image

are you using the shcdules endpoint ?it gives the hour of classes that should be include it

**Review by claugp06 — APPROVED** [review]
Good job arranging all the feedback given and fixing them. Now it is shown in a best way more clear for the user, well done!

**Review by FranciscoRossoR — APPROVED** [review]
It seems to work correctly, good job keeping up with all the feedback.

**Review by marnunrey2 — COMMENTED** [review]
Perfect, it works as expected, well done!

**Pull request merged**
