### PR TITLE
Feature/102-Kids-Evaluation

### PR DESCRIPTION
**Pull request by claugp06**
The evaluation system for daily and yearly evaluation has been created.
It can be check following the next steps:

1. The yearly evaluation can be checked trought this route: [http://localhost:3000/Educadores/ni%C3%B1os/evaluacionAnual](url)
2. A card with the picture, the name, the surname and the actual year are been showed.
3. If you want to evaluate, press the "Editar" button an window will be open.
4. You can choose the grade, wirte the comment and the date
5. For the yearly evaluation, a condition has been created: it can be only created once but the value of the grade can be update it
6. The button "Contactar" shows the contact info from the Family of the student
7. The daily evaluation follows a similar approach but the are some diffenreces. The route is [http://localhost:3000/Educadores/ni%C3%B1os/evaluacionDiaria](url)
8. It can be created more than once, because it is per day evaluation. The one shown on the screen it is the latest one been evaluated.
9. In this case, if the student has been already evaluate for that date it will be updated and if it has not been evaluated a new entry with the data will be created.
10. It also has a contact button with info to contact with the family

### CODE REVIEW

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
When I try to post or update an evaluation it doesn't work properly, nothing tells me whether it's alright or not and nothing changes when I access our API manually

**Review by fracalrod3 — APPROVED** [review]
Just tested it and everyhting works fine, good job!

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
The annual evaluation is not working because the student is not in a lesson with that evaluation type:
image

**Comment by claugp06** [comment]
@marnunrey2  I saw that I will talk with Pablo to see how the backend it is done and the changes that should be done so it works as the NGO expects and needs.

**Comment by marnunrey2** [comment]
> @marnunrey2 I saw that I will talk with Pablo to see how the backend it is done and the changes that should be done so it works as the NGO expects and needs.

Perfect, thanks!

**Review by marnunrey2 — APPROVED** [review]
Good job!

**Review by marnunrey2 — APPROVED** [review]
Good job!

**Pull request merged**
