### PR TITLE
Fix/259-attendence-volunteer

### PR DESCRIPTION
**Pull request by manbarjim2**

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Still need to be refresh so the events/classes/... I sign up appears

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
Just tried it and you need to refresh the page to see your current events, still a good job overall, a little tweak that'd be all

**Review by claugp06 — CHANGES_REQUESTED** [review]
The refresh it is not needed it anymore, good job!.
But I get now this error if I try to delete an event
image

I am using the volunteer with emaill mcast@gmail.com

**Review by claugp06 — APPROVED** [review]
Now it is working as expected, nice job!

**Review by fracalrod3 — APPROVED** [review]
Everything's working as intended

**Pull request merged**
