### PR TITLE
Feature/235 organization

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
- Created the Organization screen
- Added Organization to the header
- Added needed routes for the screen
- Corrected a few titles to make all them capital letters like the others:
    - Asociación/Dónde estamos (also fixed the typo, it was missing the accent)
    - Asociación/Transparencia
    - Asociación/Entidades Colaboradoras
    - Agenda 2030
    - Voluntarios
    - Sugerencias

### CODE REVIEW

**Review by fracalrod3 — DISMISSED** [review]
I'd appreciate a bit more quality on all images, but I understand it doesn't depen on you so about everything else, I'd say you're golden!

**Comment by FranciscoRossoR** [comment]
> I'd appreciate a bit more quality on all images, but I understand it doesn't depen on you so about everything else, I'd say you're golden!

They're the images I could take from their current website, thanks for approving anyways.

**Review by claugp06 — COMMENTED** [review]
I have a question regarding the pictures that is that if the actual organization of the NGO corresponds with that picture but overall nice job

**Comment by Ahydul** [comment]
Right now, little changes like changing the background color would make the page really ugly. I understand that those are the pictures that you could get but maybe it would be better to ask for better individual pictures of higher quality and represent them with the names next to them. If it's not possible, update the branch and I will accept the review

**Comment by FranciscoRossoR** [comment]
> Right now, little changes like changing the background color would make the page really ugly. I understand that those are the pictures that you could get but maybe it would be better to ask for better individual pictures of higher quality and represent them with the names next to them. If it's not possible, update the branch and I will accept the review

I'll finish with what I have right now but I'll take your suggestion into consideration and see what we can do, it's a good point.

**Comment by FranciscoRossoR** [comment]
- Updated board of directors.
- Deleted potentally outdated educators section.

**Review by claugp06 — APPROVED** [review]
I will approve although I hope the quality pictures can be improve.

**Review by fracalrod3 — APPROVED** [review]
Awesome, just the thing we discussed before but not your fault!

**Review by Ahydul — APPROVED** [review]
Good job

**Pull request merged**
