### PR TITLE
Fix: filter classes by message

### PR DESCRIPTION
**Pull request by claugp06**
Now, when an educator one to evaluate the kids it will be doing in the following way:

1. On the top of the screen there is a dropdown to filter by class if not class it is chosen not students are chosen
2. Once the lesson it is selected, the kids of the evaluation appears.
3. It appear for yearly and daily evaluation
Also the kids button has been taken out.

### CODE REVIEW

**Review by samrodman — APPROVED** [review]
Good job, it appears to work, with Palomino as educator i can filter the classes and see his students. When i use a educator with no lessons then it's empty. 

One thing to let you know, when i press on Contactar or Evaluaciones i get this error:

ERROR response.data.find is not a function ./src/components/Evaluation.js/EducatorEvaluationCommon/</<@http://localhost:3000/static/js/bundle.js:1305:

**Review by manbarjim2 — DISMISSED** [review]
Everything works correctly and as expected.

**Comment by claugp06** [comment]
I have made some changes regarding @samrodman  comment. Now the evaluation can be done again and the family info it is shown.
I know the style of the dropdown does not look the best but it will be fix in the styles fix and also after thinking and reconsidering the approach of the  funcionality and how was done initially I have added a toast error if a student it is evaluated for a evalution type they are not enroll
It is not the best approach but the best to apply at the moment due to time limitations, in the future this could be improved.

**Review by MartaInes — CHANGES_REQUESTED** [review]
Good job filtering by class! However, there are a few thing that you should take into account. I know that this is not part of the PR, but now that you are working with the educator screen, it would be nice if when you log in, the screen that appears is the "Evaluación diaria" and not the profile. 

Also, about the daily evaluations, the images are deformed, be careful with that. An the text could be justify in another way so it's more aesthetic.

**Comment by MartaInes** [comment]
I forgot to point out the fact that in the daily evaluation it says "Evaluación diaria" and in the yearly "Evaluación anual Niños", it should be more consistent, so it would be nice if you could remove "Niños" from the second one

**Comment by claugp06** [comment]
> Good job filtering by class! However, there are a few thing that you should take into account. I know that this is not part of the PR, but now that you are working with the educator screen, it would be nice if when you log in, the screen that appears is the "Evaluación diaria" and not the profile.
> 
> Also, about the daily evaluations, the images are deformed, be careful with that. An the text could be justify in another way so it's more aesthetic.

The style part I was not really entering as Maria is working on that and I do not want to mess up with her branch and about the redirection I thought the same so I would change it now.

**Review by MartaInes — CHANGES_REQUESTED** [review]
Thanks for changing it so fast! But, the side menu is still inconsistent, put also the "diaria" with a capital D.

**Comment by claugp06** [comment]
> Thanks for changing it so fast! But, the side menu is still inconsistent, put also the "diaria" with a capital D.

My bad did not noticed, now should be ok.

**Review by MartaInes — CHANGES_REQUESTED** [review]
Whe you are in the educator tab, that now is the "Evaluación Diaria", it is not selected in the menu. And I don't know why, but it only works the "Actividades" one.

**Review by manbarjim2 — DISMISSED** [review]
what is necessary for this functionality is correct

**Review by MartaInes — APPROVED** [review]
It's working properly now. Thanks!

**Review by manbarjim2 — APPROVED** [review]
Good work, resolving conflicts

**Review by samrodman — APPROVED** [review]
Well done consulting the feedback and fixing the minor bugs, it works and the styles can be touched upon more later.

**Pull request merged**
