### PR TITLE
Fix/42-register-and-volunteer-form-responsive

### PR DESCRIPTION
**Pull request by samrodman**
The register page and the form for volunteers should appear correctly and responsive to all.

### CODE REVIEW

**Review by MartaInes — COMMENTED** [review]
Now it adapts better to the screen size, however, in terms of style the text and input boxes should be align to the left. Also take into account the difference in sizes between the "crear cuenta" button and the "Registrarse con Google".

**Review by claugp06 — CHANGES_REQUESTED** [review]
The components of the register form are not align between them in the register. In the form of the volunteers maybe instead of having a container so big it is better to divided in two so it is more visual.

**Comment by samrodman** [comment]
I incorporated all the requests and made the volunteer form better visually as well, but i did not divide it in two. I believe it is not so long and with a slightly smaller font size it doesn't seem so big.

**Review by claugp06 — APPROVED** [review]
Looks better now, nice job

**Review by FranciscoRossoR — APPROVED** [review]
Looks quite good, well done.

**Pull request merged**
