### PR TITLE
Fix/232 meetings

### PR DESCRIPTION
**Pull request by ivaramlar**
Now, you are able to edit a meeting event in the screen "Eventos", to do it, you need to log in as an admin.

### CODE REVIEW

**Review by samrodman — DISMISSED** [review]
It works well for me, although i don't know if the time can be shown in HH:mm without the seconds. Good job though I will aprove the request to make things smoother.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Everything looks good and works but I just to small comments:
1. The first one is that it does not allows to create a meeting if the selected data is the same as today, is this intent to be like this?. I am just asking because imagine the NGO has to create an emergency meeting for the same day, they could not do it. 
2. Also, when you access to the details of the meeting on the calendar you can see a input called asistentes but all partners are welcome to attent so it should not be shown I think

**Review by claugp06 — CHANGES_REQUESTED** [review]
It is working as expected good job with that but instead of having to refresh the page to see that the meetings has been deleted or updated it should be done automatically. I believe this has already be done in other parts of the web page and I think it was done with events

**Comment by ivaramlar** [comment]
> It is working as expected good job with that but instead of having to refresh the page to see that the meetings has been deleted or updated it should be done automatically. I believe this has already be done in other parts of the web page and I think it was done with events

The feature has been implemented following the feature of edit and delete events. If we implement the option refresh the page automatically, the toast messages are not going to be shown because the refresh not take to count the toast.

**Comment by claugp06** [comment]
> > It is working as expected good job with that but instead of having to refresh the page to see that the meetings has been deleted or updated it should be done automatically. I believe this has already be done in other parts of the web page and I think it was done with events
> 
> The feature has been implemented following the feature of edit and delete events. If we implement the option refresh the page automatically, the toast messages are not going to be shown because the refresh not take to count the toast.

Ah I did not know, in that case we just leave it as it is done at the moment

**Review by claugp06 — APPROVED** [review]
Having in consideration the comment you made about the toast confirmation messages, I will aprove this pr

**Review by fracalrod3 — APPROVED** [review]
All seems to be working fine, and considering what's been previously discussed here, it's an overall great job! keep it up!

**Pull request merged**
