### PR TITLE
Fix/101-admin-families

### PR DESCRIPTION
**Pull request by marnunrey2**
In this PR we are modifying the admin screen for families so it includes the info from the backend. 

The styles are not taken into account since there is another branch for fixing the styles. Also, we are expecting a response from the ong manager about more information she wants to include in this screen.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The contents inside the blue card are not align. Also they are two big for the info they have

**Comment by marnunrey2** [comment]
> The contents inside the blue card are not align. Also they are two big for the info they have

I said on the comment not to focus on the styles because they will be fixed in the issue called fix/82-sytes

**Review by claugp06 — CHANGES_REQUESTED** [review]
The user family includes an image that can be taken from the api and should be use and shown in the family information card. One question, the request of families cannot be yet implemented because of the backend?

**Review by claugp06 — APPROVED** [review]
Ok,perfect. Good to know, just making sure that we do not forget anything.

**Review by samrodman — CHANGES_REQUESTED** [review]
Taking into account everything you talked with the leader then the PR is working well. However, the info you got from the backend, shouldn't it be modified to suit the admin better?
There's info in english like Curso: THREE_YEARS or  FOURTH_PRIMARY which is the raw data. And Evaluación is missing an accent. Please let me know if this is for later or if you can change it quickly, thanks!

**Comment by claugp06** [comment]
@samrodman  the changes from the backend will be done and once it is updated it will be changed automatically in the frontend so that's not a big issue

**Review by samrodman — APPROVED** [review]

**Pull request merged**
