### PR TITLE
feature/175 social log in

### PR DESCRIPTION
**Pull request by Ahydul**
Added social login in with google account

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
For the next time try to give a more detail explanation in the description of the PR. Secondly, I have tried to use the social log in implementation using the last changes of develop and gives this error 
image
Apart from that if only the google account it is going to be use in the log in, it should be taken out from the register and if it going to be use implement. 
Also (even I know it is not on your task), right now the register it is not working with the changes could you have a look over it?

**Review by marnunrey2 — COMMENTED** [review]
At first I get the same error as claudia but when clicking on "continuar con google" it does nothing and shows this error in the console:
```
Access to XMLHttpRequest at 'http://127.0.0.1:8000/api/auth/o/google-oauth2/?redirect_uri=http://127.0.0.1:3000/iniciar-sesion/' from origin 'http://localhost:3000' has been blocked by CORS policy: 
The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. 
The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```
Also, for log in in with google I guess that firstly there needs to be a register with google implemented.

**Comment by Ahydul** [comment]
I forgot to update the comment. You need to use 127.0.0.1 and not localhost. Also I fix in the backend is on the way. We need that fix for this to work.

**Comment by Ahydul** [comment]
The pr is merged, use the last version of develop in the backend

**Comment by claugp06** [comment]
> The pr is merged, use the last version of develop in the backend

Could you please be more explicit what you have done in this pr. Have ypu fixed the log in and register or only done the social log in?

**Review by claugp06 — CHANGES_REQUESTED** [review]
I get this error when trying to access the social log in. 
image
and I cannot try it. For the moment, fix the normal log in and register so it works with backend and leave this more to the side, there is things with a higher priority

**Review by marnunrey2 — COMMENTED** [review]
I also get the same error as claudia. I executed it from microsoft edge and this is the error message I get which might be more explicative than the error shown to claudia:
image

**Comment by Ahydul** [comment]
You probably are either not using last version of develop or not using 127.0.0.1 instead of localhost

**Review by claugp06 — COMMENTED** [review]
It is supposed to be working if I can log in with the acount but still be redirect to the log in?. The register with Google it is also consider as an option or not? Because if not the button should not appeared on the register form.
From my opinion I think that the log in does not make much sense becuase you do not indicate the role or anything maye it is more interested in the register were you are obliged to click a role and then redirect depending to it to following steps for the register

**Comment by Ahydul** [comment]
Commented out the social login button for now. After registering using social login the account must be activated providing a dni to a post /api/auth/activate/

**Review by claugp06 — APPROVED** [review]
The social log in without been commented worked for me but because of not having an account activation needed it, it does only redirect to the log in (right now this funcionality more to the side).

**Review by fracalrod3 — COMMENTED** [review]
Doesn't seem to do anything at the moment, unsure why it's accepted since it neither takes my data from Google nor creates a new account

**Review by fracalrod3 — APPROVED** [review]
I was told by Upper Management to accept this PR anyways, so here:

**Pull request merged**
