### PR TITLE
Feature/89 volunteers documentation

### PR DESCRIPTION
**Pull request by marnunrey2**
In this PR, I have implemented the volunteer form for its documentations. To test it, follow this steps:

1. Make sure that you are running the latest version of branch **develop** of the backend and that you have a user admin on the api you can access with (If not follow the steps using the auth/users) and
2. Go to http://localhost:3000/registrarse and complete the form selecting "**Registrarse como voluntario**" (use a valid email because you'll need it to approve and ignore the toast error if they are not too explicit because it's been implemented in another pr).
3. Once the form has been completed correctly, a toast success will appear telling you to check your email (you can check that the user has been created on http://localhost:8000/api/user/ with 'role' *VOLUNTARIO*, 'volunteer' as *null* and 'is_enabled' as *false*)
4. Go to your email and you'd have received an email from info.nexong@gmail.com with a link
5. Click on the link and click on the **POST** button. Now the account has been enabled (you can check on http://localhost:8000/api/user/ that 'is_enabled' is now *true*)
6. Go to http://localhost:3000/iniciar-sesion and log in with the email and password you have created the user.
7. Now, http://localhost:3000/voluntario/formulario should appear and you'll need to complete the form with the information asked. The download buttons are used for helping the user get the sexual offenses certificate and obtaining the proper documents it will need to upload signed, but for now you don't need to sign them, just upload a **pdf file**. Notice that if the birthdate introduced is **under 18**, 2 extra file inputs will appear. (you can check that the volunteer has been created on http://localhost:8000/api/volunteer/ and that the user in http://localhost:8000/api/user/ has attribute 'volunteer' with the id from the /api/volunteer)
8. Once the form has been completed correctly, http://localhost:3000/voluntario/espera should appear with a message and the status of it's request as **PENDIENTE**.
9. Now, open a new window and go to http://localhost:3000/iniciar-sesion. Log in with your admin profile and go to Voluntarios > Solicitudes. And you should see the user name and surname you have created.
10. 1. If you **accept** the request, the page of the user will automatically go to http://localhost:3000/voluntario/perfil.
      2. If you **decline** the request, the page of the user will still be on the http://localhost:3000/voluntario/espera, but status will have changed to **RECHAZADO**

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
It is areally good job and really nicely done and it is easy to follow thanks to such a detail description. If i have to be strcit, make sure the button are resposive for different screen sizez (i tried using it with hakf screen to be able to follow th content and the button were not shown in the expected place)

**Comment by FranciscoRossoR** [comment]
Everything works as intended when I create and reject a volunteer, but I get this error when I try to accept one.

Uncaught runtime errors:
×
ERROR
Request failed with status code 404
AxiosError: Request failed with status code 404
    at settle (http://localhost:3000/static/js/bundle.js:113075:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:111737:66)
    at Axios.request (http://localhost:3000/static/js/bundle.js:112238:41)
    at async handleAceptar (http://localhost:3000/static/js/bundle.js:2323:20)

**Review by samrodman — CHANGES_REQUESTED** [review]
Really good job in general, Maria, this was no small task!
thanks to your detailed instructions i was able to make it all work.
However the same thing happens to me as Paco. I cannot accept someones application, but only deny it.

Also, we should consider when to implement toast errors in the Formulario de Voluntario.

**Review by FranciscoRossoR — APPROVED** [review]
Everything works now, well done. Also, as the others said, thanks for the detailed description, it was really helpful.

**Review by samrodman — APPROVED** [review]

**Comment by samrodman** [comment]
thanks for fixing the issue so fast, works as intended, good work!

**Review by claugp06 — CHANGES_REQUESTED** [review]
The funcionality works as expected and the changes introduced are nice. Just two tiny things I noticied.
1. In the volunteer form more Toas message with an error could be add to indicate that not file is given/or the formart it is not accept it
2. The status message should be "Estado" in Spanish instead

**Comment by marnunrey2** [comment]
> The funcionality works as expected and the changes introduced are nice. Just two tiny things I noticied.
> 
> 1. In the volunteer form more Toas message with an error could be add to indicate that not file is given/or the formart it is not accept it
> 2. The status message should be "Estado" in Spanish instead

I expect that in the following week we'll develop more specific toast.error that's why I have not taken much detail on them, as we might even need a new component for them because it's repeated code on many diferent files

**Comment by claugp06** [comment]
> > The funcionality works as expected and the changes introduced are nice. Just two tiny things I noticied.
> > 
> > 1. In the volunteer form more Toas message with an error could be add to indicate that not file is given/or the formart it is not accept it
> > 2. The status message should be "Estado" in Spanish instead
> 
> I expect that in the following week we'll develop more specific toast.error that's why I have not taken much detail on them, as we might even need a new component for them because it's repeated code on many diferent files

You are misunderstaing some concepts I think. The toast message with the message are created directly on the frontend(you can see how in the branch I am working). For example if you go to network when not uploading a documment the validation error from the back appears so from the frontend whtat we have to do it is to show them

**Comment by marnunrey2** [comment]
> > > The funcionality works as expected and the changes introduced are nice. Just two tiny things I noticied.
> > > 
> > > 1. In the volunteer form more Toas message with an error could be add to indicate that not file is given/or the formart it is not accept it
> > > 2. The status message should be "Estado" in Spanish instead
> > 
> > 
> > I expect that in the following week we'll develop more specific toast.error that's why I have not taken much detail on them, as we might even need a new component for them because it's repeated code on many diferent files
> 
> You are misunderstaing some concepts I think. The toast message with the message are created directly on the frontend(you can see how in the branch I am working). For example if you go to network when not uploading a documment the validation error from the back appears so from the frontend whtat we have to do it is to show them

I didn't misunderstand, I know what it's suppose to show but in front we'll need to implement personalized messages because backend shows the message in english. What I'm trying to say is that we have many pages using toast errors messages and most of them are with the same message, so in the end codacy will complain about that and we'll have to create a component calling all the different toast errors. That's why at the moment I have created generic toast errors and I have implemented some more after your request

**Comment by marnunrey2** [comment]
> One question, have you done that the post you are making to the api, includes the headers?

If you look at the code, you can clearly see that it's using the headers. Otherwise, the post should not be working

**Review by claugp06 — APPROVED** [review]
My bad last review, I wanted to ask and not ask for changes if the header were in every request jus to make surre becuase at the moemnt we are working with modheader extension to ensure everything working as expectd

**Pull request merged**
