### PR TITLE
Feature/86-volunteers-profile

### PR DESCRIPTION
**Pull request by fracalrod3**
Took the freedom to create the "VolunteerLayout.js" component and...

All data is shown as intended:
image
image

### CODE REVIEW

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
image
Can't find the image.

**Review by claugp06 — CHANGES_REQUESTED** [review]
The password shouls not be shown as text it should be hide. Also, once the profile it is update, the user should be redirect again to the profile screen.

**Comment by fracalrod3** [comment]
> image Can't find the image.

I don't get that error when i load the app, it also doesn't make sense since it's there:
image

**Comment by manbarjim2** [comment]
> > image Can't find the image.
> 
> I don't get that error when i load the app, it also doesn't make sense since it's there: image

All correct, It was my problem.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
Why isn't there a button on the volunteer profile screen to edit your profile?

**Pull request closed without merging**
