### PR TITLE
Fix/174 lesson event

### PR DESCRIPTION
**Pull request by samrodman**
In this PR, there are multiple fixes and a few additions to admin Lessons and Events.
1. Log in as an admin, and go to Clases in the admin menu. Here you can see I added Ver Horarios and Crear Horario. Each show details on existing schedules and the option to create a new schedule. The creation should contain necessary validations already.  In 'Ver Horarios' i implemented the option to edit and delete, both with their respective validations as well and should work well.
2.  In Clases, following feedback from pilot users, I fixed the validations for Crear Clase and I implemented the option to filter through the list of students depending if you check 'Es clase por la mañana' or you don't, to make things easier. This also works for editing a lesson. In the Clases screen, the educator now appears well and the date is there also.
3. In the Eventos option of admin menu, you can create, edit and delete Lesson-events (actividades) . The validations should work and events, meetings and lesson-events have different colors on the calendar. I fixed other bugs as well, but there is a back-end error that doesn't allow to update lesson-events in certain cases even though they should, which will have to be fixed once i talk to someone responsible.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
Having in mind the need to fix the Codacy errors and the conflicts I will like to comment a few aspects (although I would like to add that it is a really nice job and the creation of the events and class works and satisfies the comments from the feedack)

- The idea of showing the schedules it is good but the tittles of the table are not that easy to read they get mixed between each other 
image

- The dialog for creating events or activities could be a bit bigger in general and the colors that are shown in the calendar for each of them should be different so it is easier to spot. For the changing of colors you can have a  look in the calendar for the volunteers.
Apart from that anything else to add, it is a really good job!

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Good job! Just some things to point out and make it better:
- When deleting an "horario" it should show a toast message not a window alert
- When updating an "horario" I would redirect to the "ver horario" page when it success
- when creating an "horario" I would redirect to the "ver horario" page when it success
- when creating an "horario", be careful because I manage to create the same "horario" for the same class and now it is duplicated (you might need to talk with backend)

Also, I'm not able to see admin/events. I get this error:
TypeError: axios__WEBPACK_IMPORTED_MODULE_16__.default.get(...).get is not a function

**Comment by samrodman** [comment]
> Having in mind the need to fix the Codacy errors and the conflicts I will like to comment a few aspects (although I would like to add that it is a really nice job and the creation of the events and class works and satisfies the comments from the feedack)
> 
>     * The idea of showing the schedules it is good but the tittles of the table are not that easy to read they get mixed between each other
>       image
> 
>     * The dialog for creating events or activities could be a bit bigger in general and the colors that are shown in the calendar for each of them should be different so it is easier to spot. For the changing of colors you can have a  look in the calendar for the volunteers.
>       Apart from that anything else to add, it is a really good job!

Thank you very much, i think i made the dialog bigger successfully and the colors should already be yellow for meetings, blue for events and pink for activities. I tried to fix the schedule table as you said but it's hard because we both see different things due to our devices and browsers.

**Comment by samrodman** [comment]
> Good job! Just some things to point out and make it better:
> 
>     * When deleting an "horario" it should show a toast message not a window alert
> 
>     * When updating an "horario" I would redirect to the "ver horario" page when it success
> 
>     * when creating an "horario" I would redirect to the "ver horario" page when it success
> 
>     * when creating an "horario", be careful because I manage to create the same "horario" for the same class and now it is duplicated (you might need to talk with backend)
> 
> 
> Also, I'm not able to see admin/events. I get this error: TypeError: axios__WEBPACK_IMPORTED_MODULE_16__.default.get(...).get is not a function

that was due to me merging develop again, I fixed it quickly, thanks for the feedback! I'll implement the toast errors now and about redirecting It could work either way but I might do that in another PR so I do it everywhere it needs it . Thanks again!

**Review by claugp06 — CHANGES_REQUESTED** [review]
Good job fixing the issues of Codacy. About the table, use @media for the style that helps for been more responsive in smaller screens and try to use % or rem (it still does not look the best on my device)
Apart from that I am trying to create an actuvity but I get this error
image

And I don't really understand because all the inputs are completed. Also keep in mind that an event of 1 min right now can be created which it is not realistic put some limit for this (for example the duration is at least 30 min/1 hour)

**Comment by samrodman** [comment]
> Good job fixing the issues of Codacy. About the table, use @media for the style that helps for been more responsive in smaller screens and try to use % or rem (it still does not look the best on my device) Apart from that I am trying to create an actuvity but I get this error image
> 
> And I don't really understand because all the inputs are completed. Also keep in mind that an event of 1 min right now can be created which it is not realistic put some limit for this (for example the duration is at least 30 min/1 hour)

I fixed the issues where it wasn't creating the lesson-event, a little validation slipped in last changes, sorry. Also good idea, I made the limit to 15 minutes, you cannot create or update a event or lesson event in less time. 

I'm also happy to say I figured out a way to implement an important feedback issue, now in recurring events, you can choose from daily or weekly. This way, if an event lasts a few days you can easily choose Diario and create multiple repeated events and you can edit them separately so volunteers could for example join them and not affect the others. This is the best way to do it I'm almost certain.

I'm having issues witht the schedule table though... i hope it's a bit better now, i tried the @media implementation, thank you

**Review by claugp06 — CHANGES_REQUESTED** [review]
The style of the table it is not resposive yet but this can be fixed next week where the styles will be again touch to make it more responisve for phones. As you have done with events to avoid the creation of events of 1 minutes should be also do for activities because at the moment it allows you to create activities of 1 min.

**Review by marnunrey2 — APPROVED** [review]
Nice work!

**Review by claugp06 — COMMENTED** [review]
Please merge the branch with the last changes of develop, right now as it is I cannot check if it works or not.

**Review by claugp06 — COMMENTED** [review]
Everything seem to work as expected but I have a doubt: when a class is created the startging date and finishing date cannot be the same (there is a toast) so that implies when a class is created the date given has to be for the whole year (imagine a class starts in October and finishes in June)

**Review by claugp06 — APPROVED** [review]
After looking the strcture of the database with the diagram I know understand more the sctrue and how it works and everything seems to be working as expected. Goo jib!

**Review by FranciscoRossoR — CHANGES_REQUESTED** [review]
Wen I try to create a schedule on a Wednesday, I get
```weekday: [""MIÉRCOLES" is not a valid choice."]```
I think it's because it's stored as "MIERCOLES" in the backend, without the accent.
Also, a minor detail that I wouldn't necessarily demand but would be nice to have, the titles of the schedules table can look a little confusing, maybe some inner borders to separate them could help.
Finally, I can't edit the existing lessons because starting time can't be in the past and I think that restriction should only be applied to finish time, but I guess that's more a backend issue so I wouldn't demand it either.

**Review by marnunrey2 — APPROVED** [review]
Everything looks fine, just fix the error Paco is getting. Good job

**Comment by samrodman** [comment]
> Wen I try to create a schedule on a Wednesday, I get `weekday: [""MIÉRCOLES" is not a valid choice."]` I think it's because it's stored as "MIERCOLES" in the backend, without the accent.
> 
> Also, a minor detail that I wouldn't necessarily demand but would be nice to have, the titles of the schedules table can look a little confusing, maybe some inner borders to separate them could help.
> 
> Finally, I can't edit the existing lessons because starting time can't be in the past and I think that restriction should only be applied to finish time, but I guess that's more a backend issue so I wouldn't demand it either.

Thanks for the sharp eye Paco, I fixed it quickly!

**Review by FranciscoRossoR — APPROVED** [review]
It works now, well done and thanks for listening.

**Review by marnunrey2 — APPROVED** [review]
Good job!

**Pull request merged**
