### PR TITLE
Feature/165-Recurring donations

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
- Fixed the partner regsiter to match the latest backend version.
- Changed the placeholder message to a request of account confirmation.

To test this feature:
1. Go to [http://localhost:3000/donaciones](http://localhost:3000/donaciones).
2. Create a new partner account in the right half of the screen.
3. If everithing goes alright, a request for confirmation will be shown.
4. Check your email for a message from [info.nexong@gmail.com](info.nexong@gmail.com).
5. Click the link in the message and click the "POST" button in the page you will be redirected to.
6. Go to [http://localhost:3000/iniciar-sesion](http://localhost:3000/iniciar-sesion) and log in with the user you just created. You should be sent to the partners section of the app.

### CODE REVIEW

**Review by FelixoGudiel — CHANGES_REQUESTED** [review]
I cannot try the functionality of your system because it is not getting the token it recieves in the register. This is probably a little mistake caused because you still use the modheader, the plugin which we should stop using. Instead of it, add the recieved token to the header, in this way:

```
 const handleLogin = async (event) => {
        event.preventDefault();
        try {
            const response = await axios.post(`${API_ENDPOINT}auth/jwt/create/`, {
                email: email,
                password: password,
            });
            const { access: accessToken, refresh: refreshToken } = response.data;
            localStorage.setItem('accessToken', accessToken);
            localStorage.setItem('refreshToken', refreshToken);
    
            console.log('Logged in, access token:', accessToken);
    
            // Get all users
            const usersResponse = await axios.get(`${API_ENDPOINT}user/`, {
                headers: {
                  'Authorization': `Bearer ${accessToken}`
                }});
            const users = usersResponse.data;
    
            // Find the user that matches the logged-in user's email
            const user = users.find(user => user.email === email);
    
            console.log('User data:', user);
    
            if (user.role === 'VOLUNTARIO') {
                navigate('/voluntario/agenda');
            } else if (user.role === 'FAMILIA') {
                navigate('/familia/perfil');
            } else if (user.role === 'SOCIO') {
                navigate('/socio/calendario');
            } else if (user.role === 'EDUCADOR') {
                navigate('/educador');
            } else {
                navigate(`/admin/voluntarios`);
            }
    
            localStorage.setItem('userId', user.id);
    
        } catch (error) {
            console.error('Error during login:', error);
            toast.error('Contraseña o correo incorrecto');
        }
    };
    const marginTop = useAdjustMargin();
```

Also, if you could make the file upload button a little more like the rest of the application, it would be a nice touch!

**Review by marnunrey2 — COMMENTED** [review]
Backend has implemented a new attribute for user and it's mandatory for doing a post. This is the error message:
```
is_agreed: ['User must accept terms and conditions.']
```
I know it's not your fault but I cannot test your functionality without that. The solution is simple. Just add a checkbox at the end of the form asking the user to agree on the terms conditions. And if you could copy the code you implement for that on the register screen, it will give us less problems in the future

**Comment by FranciscoRossoR** [comment]
- Added checkbox for use terms and conditions.
- Tried to implement access token.

**Review by claugp06 — CHANGES_REQUESTED** [review]
I tried to test the implementation but I get a not allowed error (405) related with a Post operation on the api/user which I do not really understand why happends. Also, the is_agreed should appear on the screen as a checkbox and i cannot see it

**Review by marnunrey2 — COMMENTED** [review]
Everything works as you said, good job! Just to point something out, make sure that a user that is under 18 cannot create an account because it doesn't make sense in this case

**Comment by marnunrey2** [comment]
Also, I forgot to mention, the inscription file should be the one provided from the NGO so I would add a button next to the input file for the partner to upload completed

**Comment by FranciscoRossoR** [comment]
- Added a download link for the papers to sign.
- Added a restriction so you can only become a partner if you're over 18.

**Review by FelixoGudiel — CHANGES_REQUESTED** [review]
This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:

contact the backend to cahnge the permissions of creating these entities (what I would do!)

create an empty user,use its token to create a partner, then update the user with the partner info

**Review by claugp06 — CHANGES_REQUESTED** [review]
I cannot try at all, I am using mod header and i can log in with an account but i cannot do your register I get a 401 error. I agree with Felix about the better approach strategie

**Comment by claugp06** [comment]
After reconsidering a bit the things and seeing how things are in the backend implement it. I think it would be better approach to include a checbox in the register for partners and once it is done, do similar as Maria(do a form with th data needed for the partner) and once it is complete go to partner screens.

**Comment by FranciscoRossoR** [comment]
> This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:
> 
> contact the backend to cahnge the permissions of creating these entities (what I would do!)
> 
> create an empty user,use its token to create a partner, then update the user with the partner info

After redesigning the task, the process will be:
1. Registering the user.
2. Confirming the account via email.
3. Logging in and submitting the remaining data for a partner user.

Would your advice apply anyways or I can go with what I have?

**Comment by claugp06** [comment]
> > This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:
> > contact the backend to cahnge the permissions of creating these entities (what I would do!)
> > create an empty user,use its token to create a partner, then update the user with the partner info
> 
> After redesigning the task, the process will be:
> 
> 1. Registering the user.
> 2. Confirming the account via email.
> 3. Logging in and submitting the remaining data for a partner user.
> 
> Would your advice apply anyways or I can go with what I have?

What do you mean with apply anyway?Are you considering adding a checkbox for partners and in donations just leaving punctual donations?

**Comment by claugp06** [comment]
> > > This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:
> > > contact the backend to cahnge the permissions of creating these entities (what I would do!)
> > > create an empty user,use its token to create a partner, then update the user with the partner info
> > 
> > 
> > After redesigning the task, the process will be:
> > 
> > 1. Registering the user.
> > 2. Confirming the account via email.
> > 3. Logging in and submitting the remaining data for a partner user.
> > 
> > Would your advice apply anyways or I can go with what I have?
> 
> What do you mean with apply anyway?Are you considering adding a checkbox for partners and in donations just leaving punctual donations?
Sounds good, if any problem appear feel free to ask

**Comment by FranciscoRossoR** [comment]
> > > This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:
> > > contact the backend to cahnge the permissions of creating these entities (what I would do!)
> > > create an empty user,use its token to create a partner, then update the user with the partner info
> > 
> > 
> > After redesigning the task, the process will be:
> > 
> > 1. Registering the user.
> > 2. Confirming the account via email.
> > 3. Logging in and submitting the remaining data for a partner user.
> > 
> > Would your advice apply anyways or I can go with what I have?
> 
> What do you mean with apply anyway?Are you considering adding a checkbox for partners and in donations just leaving punctual donations?

Instead of just removing recurring donations from the Donations screen and leaving the punctual ones alone, I'm considering keeping both halves of the screen and changing the recurring donations register form to a link to the register page so you can become a partner.

**Comment by claugp06** [comment]
> > > > This feature does not work because you are trying to add a partner without atoken, because there is no user created. I ahve thought of two alternatives:
> > > > contact the backend to cahnge the permissions of creating these entities (what I would do!)
> > > > create an empty user,use its token to create a partner, then update the user with the partner info
> > > 
> > > 
> > > After redesigning the task, the process will be:
> > > 
> > > 1. Registering the user.
> > > 2. Confirming the account via email.
> > > 3. Logging in and submitting the remaining data for a partner user.
> > > 
> > > Would your advice apply anyways or I can go with what I have?
> > 
> > 
> > What do you mean with apply anyway?Are you considering adding a checkbox for partners and in donations just leaving punctual donations?
> 
> Instead of just removing recurring donations from the Donations screen and leaving the punctual ones alone, I'm considering keeping both halves of the screen and changing the recurring donations register form to a link to the register page so you can become a partner.

Maybe it is not a bad idea that in some way it is indicated in the donation how to become a partner to the register as you commented but leaving the two halves of the screen doesn't seem the best to me because maybe the right half gets really empty but if you think it can look nice just go for it and do it!

**Comment by FranciscoRossoR** [comment]
- Moved the recurring donations register to general register.
- Fixed Donations screen.

To test the register/login functionality:
1. Go to [http://localhost:3000/registrarse](http://localhost:3000/registrarse) and register as a new partner.
2. Activate your new account by clicking the link in the mail by info.nexong@gmail.com.
3. Go to [http://localhost:3000/iniciar-sesion](http://localhost:3000/iniciar-sesion) to log in as the user you just created.
4. A form to complete the remaining partner data will appear.
5. If everything goes alright, you will be redirected to [http://localhost:3000/socio/calendario](http://localhost:3000/socio/calendario).

**Review by claugp06 — CHANGES_REQUESTED** [review]
The form and register for the partners  is working but I have a few commentd to made

1. Are you using the last changes available? I am just saying that because the merge with the privacy policy was include and it is not shown
2. In the donation screen if the right container for recurrent donation could be more down it would look nicer but I do not know if it is possible
3. The last thing is that you put some timer so the redirection to the partners calendar takes a bit longer because I cannot almost see the toast message of success, it is really fast the change

**Review by marnunrey2 — COMMENTED** [review]
Everything working as expected, good job! 

Just something to point out, the file that needs to be downloaded on the partner form should be the one that the NGO gave us, not the volunteers file

**Review by FelixoGudiel — APPROVED** [review]
Great job!

**Review by marnunrey2 — DISMISSED** [review]
Good job!

**Comment by FranciscoRossoR** [comment]
> The form and register for the partners is working but I have a few commentd to made
> 
> 1. Are you using the last changes available? I am just saying that because the merge with the privacy policy was include and it is not shown
> 2. In the donation screen if the right container for recurrent donation could be more down it would look nicer but I do not know if it is possible
> 3. The last thing is that you put some timer so the redirection to the partners calendar takes a bit longer because I cannot almost see the toast message of success, it is really fast the change

About **2**, I think putting the container in the middle instead of the top would just leave so much blank space over the box, maybe it wouldn't even be completely visible.

About **3**, with all due respect I don't think it's a good idea to slow down the app, instead we could not use messages when we redirect or try some way to make them appear in the new page, but not making it slower for the user to reach the new page.

**Review by claugp06 — APPROVED** [review]
Everything seems to be working as expected.Good job!

**Comment by FranciscoRossoR** [comment]
Sorry about the requests for review, currently the punctual donation doesn't work in this branch so I don't know if I should consider this done yet.

**Comment by FranciscoRossoR** [comment]
> Sorry about the requests for review, currently the punctual donation doesn't work in this branch so I don't know if I should consider this done yet.

Fixed now, you can review.

**Review by FelixoGudiel — DISMISSED** [review]
Despite all the changes in the develop, you have managed to keep functional this feature. Great job!

**Comment by FranciscoRossoR** [comment]
> I tried to check if puntual donations works and I get this error image I have the last changes of the back and your branch

The problem is, punctual donations still depend on the modheader (you can try it out). Seems like it hasn't been implemented yet and I didn't consider it a part of my task.

**Review by claugp06 — APPROVED** [review]
The part of punctual donation will be done as a fix assign to you. I will create an issue for that and the recurrent donations works as expected good job!

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Just a quick fix that you missed: you have uploaded the volunteer_registration.pdf for the partner to download, but that's not the document I meant (that is already uploaded and is for volunteers only). Partners have another document that is on out discord channel of info from manos abiertas. Also, when uploading the file, remember to change the handleDownload parameter on the button with the actual name of the file.

Also, include some toast message to tell the user that the form has been completed.

**Review by marnunrey2 — APPROVED** [review]
perfect, thanks!

**Review by FelixoGudiel — DISMISSED** [review]

**Review by claugp06 — APPROVED** [review]
Everything works and the correct document it is donwload it.

**Comment by FranciscoRossoR** [comment]
Fixed a bug where the download button for the document would also work as submit button.

**Review by claugp06 — DISMISSED** [review]
Good eye noticing that, everything works as far as I noticed

**Comment by FranciscoRossoR** [comment]
Fixed wrong correction of the merge conflicts where login changes weren't included.

**Review by marnunrey2 — APPROVED** [review]
Good job!

**Review by claugp06 — APPROVED** [review]
Everything seems ok

**Review by FelixoGudiel — APPROVED** [review]

**Pull request merged**
