### PR TITLE
Feature/11- screens for admin events, lessons and proyects

### LINKED ISSUE #11: Feature/11-Admin screen- Lesons, events, proyects

### PR DESCRIPTION
**Pull request by manbarjim2**

### CODE REVIEW

**Comment by ivaramlar** [comment]
Your pull request is not valid, you need to extract all the files from the admin's folder and change all the files to .js instead of using .jsx

**Review by claugp06 — CHANGES_REQUESTED** [review]
Please use the styles in styles.css to maintain the same style throught the whole app. Also do not forget to include in the right side of the screen the suer log in and picture as shown in the mock ups.

**Review by MartaInes — CHANGES_REQUESTED** [review]
The event screen looks good, however the lessons and projects one are a bit more rudimental. In the projects one I understand that there is some information missing in which fields a project should have, however it would be interesnting to leave done a basic form that can be updated when we have more information about it. In terms of style, each of the screens have a different style of menu bar. Talking about the lessons one, the space should be better used, think about putting two lessons in the same row, so there's no so much empty space. And right now the "Crear clase" is way to big and it's too close to the right margin.

**Review by claugp06 — CHANGES_REQUESTED** [review]
In the class screen the content inside the container should be more to the left and there shoulld be align.The "crear clase" and the icon are not align either. In the project screen the two icons should be toghether in the right and appart from the same of the prject a description should be added.

**Review by MartaInes — APPROVED** [review]
Looking way better now, I hope that we can have all the information soon so you can finish it for good. But great job!

**Review by claugp06 — APPROVED** [review]
Good job!

**Pull request closed without merging**
