### PR TITLE
Feature/35-Pantalla-admin-socios

### PR DESCRIPTION
**Pull request by ivaramlar**

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
The screen shoud contain the side menu as it appears on the mock ups. More over the design use does not look as the mock ups design. Please, change it so it fullfills it.
You have to change the name of the PR so it fits the syntax agreed on.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
The design is a little different, please improve it.

**Review by claugp06 — CHANGES_REQUESTED** [review]
The design of the page looks good but nothing it is shown in the partners screen. Before merging this pull reuqest you should use the data from the backend to show the partners available and check if a meeting can be created.

**Review by claugp06 — CHANGES_REQUESTED** [review]
It looks good, but the editingg and deleting partners does not make much sense becuase the partners can edit their profile and unsubscribe from been a partner.

**Comment by ivaramlar** [comment]
Changed the style of the partners as it has been suggested.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Sorry, for my comment from before. After, talking with the PM she told me that the delete icon should be include it.

**Review by manbarjim2 — CHANGES_REQUESTED** [review]
It seems correct except for adding the delete button again as mentioned above.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Everything works as expected but just leave the icon of deleting not editing.

**Review by claugp06 — APPROVED** [review]
Looks good now!

**Review by manbarjim2 — APPROVED** [review]
It is well made and adapted to changes.

**Review by claugp06 — APPROVED** [review]
Looks good now

**Pull request merged**
