### PR TITLE
Fix/84-create-classes-events-projects

### PR DESCRIPTION
**Pull request by samrodman**
In this PR, we are able to get and create actual lessons and events with the api. 
LESSONS: we can see the lessons of the api on screen with its attributes. If they are too long, I opted for a scroll option in the lesson box as the best view. Then, we have a button to create a lesson that takes you to another screen, where you can fill out a form with the necessary attributes. You can select multiple students and one educator by their names.  Be careful because some students cannot be assigned to morning lessons and viceversa. The 'Volver' button takes you back to the lessons that exist. We are still awaiting for the option to properly delete and update them.

EVENTS:  we get the events in the calendar correctly, and we can create events ourselves. It should work properly and if we click on an empty day, we can create an event with the corresponding start date already chosen. If we click on a created event, we can see its info as a placeholder which will be the next step for updating the event. The event hours are not shown in the month view due to react-big-calendar and i could not find a good solution, but in the week and day view the hours can be seen. We are still waiting for the options to delete and update events.

PROJECTS - nothing has changed because it is not sure if it will be implemented in the backend. The skeleton is there just in case.

### CODE REVIEW

**Review by ivaramlar — CHANGES_REQUESTED** [review]
Firstly, it is unnecessary to be able to select negatives numbers in lesson's capacity (form lesson). In the form add new event, the problem is the same, you can select the attributes price, max volunteers and max assistants with values fewer than 0.

Secondly, all the forms all well conected with backend, so well done.

**Comment by samrodman** [comment]
Thanks for pointing it out, i fixed it quickly

**Review by claugp06 — CHANGES_REQUESTED** [review]
The blue color use for the adding of events and classes should be black. Also, when creating an event or class when there is an error of the data introduced it is not shown what it is the error. Apart from data in the screen of classes the space it is not used in a smart way, would be better if two cards with info of the classes coul appear in the same row so there is not too much white space without been used

**Comment by samrodman** [comment]
I added toast components for the validations of the forms, and also a positive success validation when submitting the form. 

npm install react-toastify --force

I fixed the styles as best i could, and if the lessonBoxes continue to be on other computers in one column we will have to look into this issue.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Without entering in the part of styles (that will be fix with Maria's brnach). I would say that the button to create an event and class when you go over it, changes to blue but it is not the same blue as the one used in the web page, it is stronger. The toast messages and creation of events and classes work as expected but the possibility to edit a class an event should be include it and it is not done

**Comment by samrodman** [comment]
I fixed the color of the create buttons, i also added the functionality to delete and update events and lessons. When deleting, a pop up appears for confirmation. The put methods have the necessary validations with toast as well.

**Review by claugp06 — CHANGES_REQUESTED** [review]
In the events screen, the title for the edit it is in english. Also I would recommend that instead of editar, used enviar for sending the data once it is complete with the data.

**Review by claugp06 — APPROVED** [review]
Well done addressing all the suggested changes. It looks good now.

**Review by manbarjim2 — APPROVED** [review]
Well developed and applying revisions. Good idea to apply to toastify.

**Review by claugp06 — APPROVED** [review]
Nice job

**Pull request merged**
