### PR TITLE
Fix/163-volunteers-attendance

### PR DESCRIPTION
**Pull request by manbarjim2**
Instead of an alert message when removing the current volunteer from the event or class, a Toast message is displayed. All the different types of activities that a volunteer can attend are also shown indicating the name and what type of activity it is: event, lesson event.

### CODE REVIEW

**Comment by manbarjim2** [comment]
To test it,
1. log in as a volunteer
2. join an event and a lesson event
3. see what appears indicating its name and type
4. you can stop being attached to both

**Review by claugp06 — CHANGES_REQUESTED** [review]
Hey, I tried to check the funcionality. But you ara working with main instead of develop (which shoul be used as it was commented by the backend part) and for you the log in it is wokring but from develop does not. Also, there is not event created and it gives a 401 error when trying to create it (I know it is not part but if the need of creating an event it is needed it should be working with the token)

**Review by claugp06 — CHANGES_REQUESTED** [review]
I sign un for an event that appeared and it worked but when I try to see my attendence I am not show anything and I am giving an error which cause becuase the endpoint used for taking the actual user is not auth/me but auth/users/me. I change to see if with that it worked but because we have to use the modheader (until the fix of @FelixoGudiel  it is completed it),and I am not showed anything

**Comment by manbarjim2** [comment]
The functionality is applied, but must be reloaded when they do not appear due to loading time.

**Comment by manbarjim2** [comment]
> Works ok but having to reload due to loading times is definitely a problem, is there any way you could try and improve that?

I have thought that the screen is constantly reloading, but it seems heavy to me.

**Review by claugp06 — CHANGES_REQUESTED** [review]
I think if the volunteer does not have any event to attend a message of not events to attend should be shown

**Review by claugp06 — CHANGES_REQUESTED** [review]
Fix the conflitcs that are shown, merge with develop (the log and register funcionalities are now in develop) and the message of not events it is nice but should be in the middle of the screen.

**Review by claugp06 — COMMENTED** [review]
I cannot try this implementation at the moment at it has error due to not been merge with the last changes of develop

**Review by claugp06 — CHANGES_REQUESTED** [review]
I am using a volunteer from the populate and I get this error when trying to be include in an event. 
image

I wanted to check if I sign in for somenthing it is shown on the attendence. Also to show there is not events that the volunteer is assisting, do it in the same way as admin when there is no family requests or volunteers request for maintining an uniform style thorugh the web app

**Review by claugp06 — CHANGES_REQUESTED** [review]
It is working now and the events you are sign in are shown but just a small detail I noticed: the titles of the table for example "evento" should appear in bold so it is more attractive to the eye

**Review by claugp06 — CHANGES_REQUESTED** [review]
Please fix the style of the table it is not resposive at all and it is too big (in my laptop at least)
image

**Comment by manbarjim2** [comment]
> Please fix the style of the table it is not resposive at all and it is too big (in my laptop at least) image

I have been using the styles we have in common so that it would be homogeneous, I will change it.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Change the toast messsages to spanish. Also, the volunteer I am using from the populate mcast@gmail.com it is sign uo for an event but does not allowed me to delete it.

**Comment by manbarjim2** [comment]
> Change the toast messsages to spanish. Also, the volunteer I am using from the populate [mcast@gmail.com](mailto:mcast@gmail.com) it is sign uo for an event but does not allowed me to delete it.

All toast messages are in Spanish.

**Comment by manbarjim2** [comment]
> Change the toast messsages to spanish. Also, the volunteer I am using from the populate [mcast@gmail.com](mailto:mcast@gmail.com) it is sign uo for an event but does not allowed me to delete it.

That volunteer belonged to an event prior to the current date, it should not appear, that is why it could not be deleted.

**Comment by claugp06** [comment]
> > Change the toast messsages to spanish. Also, the volunteer I am using from the populate [mcast@gmail.com](mailto:mcast@gmail.com) it is sign uo for an event but does not allowed me to delete it.
> 
> That volunteer belonged to an event prior to the current date, it should not appear, that is why it could not be deleted.

Then a message about that should be shown

**Comment by manbarjim2** [comment]
> > > Change the toast messsages to spanish. Also, the volunteer I am using from the populate [mcast@gmail.com](mailto:mcast@gmail.com) it is sign uo for an event but does not allowed me to delete it.
> > 
> > 
> > That volunteer belonged to an event prior to the current date, it should not appear, that is why it could not be deleted.
> 
> Then a message about that should be shown

I have already solved it, past events do not appear in the attendances

**Review by MartaInes — CHANGES_REQUESTED** [review]
In general you did a quite good job. However, when you delete your assistance of an event, the event disappears in the calendar. It should remain there and only the color should change.

**Comment by manbarjim2** [comment]
> In general you did a quite good job. However, when you delete your assistance of an event, the event disappears in the calendar. It should remain there and only the color should change.

I have tried several times and that doesn't happen to me, could you specify when it happened to you.

**Review by claugp06 — CHANGES_REQUESTED** [review]
I sign in for an event (it works the color changes) but not event is shown in the attendance.Also a small question in the calendar the colours changes depending if it s an event, lesson event or class?

**Comment by manbarjim2** [comment]
> I sign in for an event (it works the color changes) but not event is shown in the attendance.Also a small question in the calendar the colours changes depending if it s an event, lesson event or class?

That is due to the backend loading time, change it. In the attendance record I don't see any sense in them appearing in a different color.

**Comment by claugp06** [comment]
> > I sign in for an event (it works the color changes) but not event is shown in the attendance.Also a small question in the calendar the colours changes depending if it s an event, lesson event or class?
> 
> That is due to the backend loading time, change it. In the attendance record I don't see any sense in them appearing in a different color.

I meant in the volunteer calendar and it should not be a loading from the back because if not a 429 error should appear which is not the case

**Review by claugp06 — CHANGES_REQUESTED** [review]
There is conflicts issues when trying this pr and errors get shwon

**Comment by manbarjim2** [comment]
> There is conflicts issues when trying this pr and errors get shwon

Currently I have just tested it with different users and it allows me to join an event or lesson event as well as see it in the attendance list and then delete myself from it.
When you join an event the page updates and goes to the current month, but if you go to the month of the event it now appears in a different color.

**Review by claugp06 — COMMENTED** [review]
There is some issue because nothing it is shown in the calendar even it shoul because theare are events that are elaready created and I check with the admin and nothing shown

**Comment by manbarjim2** [comment]
image
image
image
image
image
image
image

The events appear for me and everything works correctly

**Review by claugp06 — APPROVED** [review]
Now it is working nice job

**Review by claugp06 — APPROVED** [review]
The volunteer attendence is working

**Review by marnunrey2 — APPROVED** [review]
It works as expected, good job!

**Review by MartaInes — APPROVED** [review]
It's working fine. Great job!

**Pull request merged**
